src/Sparse/Module.jl

the method at https://github.com/thofma/Hecke.jl/blob/96d3f56e6e34fc7ee2bbc3c5631a94b7cb7b1214/src/NfMaxOrd/Unit/Reduction.jl#L80 is defined on Base types, which can change the behavior of unrelated code

Do not extend Base.reduce

---

src/NfOrd/Hensel.jl
src/NumField/NfAbs/Elem.jl

Assuming b is a mathematically integral element
- do not clear the visible denominator
- rely on the f'(alpha) trick to work in the field
- provide is_integral as a flag
- provide ispower for order-elemts this way
required some minor work in the hensel core

try to imporve ispower for integral elements

---

src/LocalField/Poly.jl

in Hensel over q-adic code
```julia
julia> K = QadicField(43,2,20)
Unramified extension of 43-adic numbers of degree 2
julia> R,x = PolynomialRing(K, "x")
(Univariate Polynomial Ring in x over Unramified extension of 43-adic numbers of degree 2, x)
julia> Hecke.Hensel_factorization(x^6 - x^5 - 7*x^4 + 2*x^3 + 7*x^2 - 2*x - 1)
ERROR: UndefVarError: map_coeff not defined
Stacktrace:
[1] Hecke.HenselCtxdr{qadic}(::AbstractAlgebra.Generic.Poly{qadic}, ::Array{fq_nmod_poly,1}) at /Users/alex/.julia/packages/Hecke/Am91n/src/LocalField/Poly.jl:577
[2] Hensel_factorization(::AbstractAlgebra.Generic.Poly{qadic}) at /Users/alex/.julia/packages/Hecke/Am91n/src/LocalField/Poly.jl:545
[3] top-level scope at REPL[4]:1
```

fix incorrect function call to map_coeff?

---

src/LocalField/qAdic.jl

trace seems to be very broken to me, it gives random output (something is not being initialised properly? but norm looks like it works now)

fix coefficient_ring call in trace / norm of qadics

---

src/HeckeTypes.jl

... and similarly for group elements
This requires https://github.com/Nemocas/AbstractAlgebra.jl/pull/567 to be merged first. I am just submitting it now so I won't forget later.

Replace Nemo.Group by AbstractAlgebra.AdditiveGroup

---

src/AlgAss/AbsAlgAss.jl
src/AlgAss/Ideal.jl
src/EllCrv/Finite.jl
src/Misc/Integer.jl
src/NfOrd/ResidueRing.jl
test/AlgAss/AbsAlgAss.jl
test/AlgAss/Ideal.jl
test/EllCrv/Finite.jl
test/NfOrd/ResidueRing.jl
test/runtests.jl

This is a modest first step, which concerns only `rand` methods taking only one object (i.e. this does not use RandomExtensions.jl).
This PR depends on the merged https://github.com/Nemocas/Nemo.jl/pull/878, which is not a breaking change (so a Nemo patch release could be made).

update few rand methods according to the Random API

---

test/LocalField/Conjugates.jl

@fieker julia changed the hashing for Integers (including BigInt) on master here: https://github.com/JuliaLang/julia/pull/38031, which broke the LocalField tests. My change here make it pass again, but I am wondering if there is an underlying issue we need to fix?

Fix for julia master

---

.github/workflows/CI.yml

... this was lost with the removal of Travis (resp. with Travis stopping to work).
However, for the final step (the actual deployment) to work, someone with admin rights for this repo may have to set a `DOCUMENTER_KEY`. To generate one, you can do this:
```julia
julia> using DocumenterTools, Hecke
julia> DocumenterTools.genkeys(Hecke)
```
Then go to "Settings" -> "Deploy Keys" (should be something like <https://github.com/thofma/Hecke.jl/settings/keys>) and add it there.

Deploy documentation to website using GitHub Actions

---

src/LocalField/Conjugates.jl
src/Misc/toHecke.jl
src/NumField/NfAbs/PolyFact.jl

toHecke: fmpz_mat: change format to allow larger matrices
zassenhaus: allow non-integral (wrt. equation order) factors
van_hoej: yet another iteration of precision
qAdicConj: do NOT compute the maximal order....

Various, unfortunately:

---

examples/MPolyFact.jl
examples/mfactor.jl

It would be nice to have some test code for the abs factorer - i.e. examples that currently are supposed to work.
The previous code was doing a power series lift (mod y^d) so all of the coefficients on y^d, y^(d+1),... of the error were junk. The last boolean argument of pfrac controls this.

switch to AA's partial fractions

---

src/Misc/Poly.jl

@wbhart This function was removed, but the export statement was not adjusted. Only shows up as warnings in Oscar.

Don't export functions that don't exist

---

examples/MPolyFact.jl

I am in no way claiming this is a good interface for factor_absolute. It is just the first thing I threw together to get the answer out.
There is a problem in recognizing abs irreducible stuff (the code in this pr has a slightly better error message):
```
julia> using Hecke
julia> Hecke.example("MPolyFact.jl")
julia> Qxy,(x,y)=QQ["x","y"];MPolyFact.absolute_bivariate_factorisation(x^2 + 2*y^2 + 2)
ERROR: AssertionError: factorization is not correct mod p^1
Stacktrace:
[1] lift_prime_power(a::fmpq_mpoly, fac::Vector{AbstractAlgebra.Generic.MPoly{qadic}}, alphas::Vector{Int64}, kstart::Int64, kstop::Int64)

Very first start factor absolute

---

src/Misc/Matrix.jl
test/GrpAb/GrpAbFinGen.jl

We were passing through diagonal matrices, even if the diagonal had negative entries.

Fix bug in Smith normal form

---

src/NfOrd/Clgp/Map.jl
test/NfOrd/Ideal.jl

If `princ_gen` was already set, there was a conversion missing.

Fix bug in isprincipal_fac_elem

---

src/Misc/Integer.jl

See https://github.com/Nemocas/Nemo.jl/pull/985

Remove ^(::fmpz, ::fmpz) because of (probable) implementation in Nemo

---

src/Misc/Poly.jl

I guess https://github.com/Nemocas/AbstractAlgebra.jl/pull/887 will require this fix before it passes.

Fix poly ring

---

src/QuadForm/MassQuad.jl
test/QuadForm/MassQuad.jl

`_minkowski_multiple(1)` is 2 not 1 (there is a 1x1 rational matrix
group of order 2). This also agrees with the formulas.
Call `bernoulli_cache` for a very minor potential performance boost.
Allow `_minkowski_multiple(QQ, n)` as alias for `_minkowski_multiple(n)`,
to make it easier to write code uniformly dealing with both number fields
and the rationals.
Remove unused `_multiple_of_finite_group_order_glnz`

_minkowski_multiple: a fix, some tweaking, and tests

---

src/NumField/NfRel/absolute_field.jl

The argument was named L but the text referenced also K. I am guessing those are the same. Since all actual methods I saw for this function call their first parameter `K` and not `L`, I chose to replace `L` by `K` instead of the other way around.

Fix docstring for absolute_simple_field

---

src/NumField/NfAbs/NfAbs.jl

A quadratic field extension should have a polynomial of degree 2, not n.
I found the typo here: https://oscar-system.github.io/Oscar.jl/stable/Hecke/number_fields/fields/#quadratic_field-Tuple{fmpz}

fix documentation typo for quadratic_field

---

src/AlgAssAbsOrd/PIP.jl
src/Deprecations.jl
src/Grp/GenGrp.jl
src/Grp/Morphisms.jl

Closes https://github.com/oscar-system/Oscar.jl/issues/667.

Rename subgroup -> sub

---

src/NumFieldOrd/NfOrd/Clgp/Map.jl
src/Sparse/Matrix.jl

Add option to track coprime factorization on the level of ideals in the `isprincipal_fac_elem` call.

Track factorization in `isprincipal_fac_elem`

---

Project.toml
src/AlgAss/AlgMat.jl
src/AlgAss/AlgMatElem.jl
src/AlgAss/Elem.jl
src/AlgAss/Types.jl
src/AlgAssAbsOrd/Conjugacy/Conjugacy.jl

- AA does not have matrices for noncommutative rings (yet)
- We make our algberas/orders subtypes of Ring (to make matrices work)
- But we want NCPolynomialRing for polynomials over this ring

Hack around non-existing matrices for noncommutative rings (Fixes #419)

---

src/LocalField/neq.jl
src/Misc/RelFiniteField.jl
test/Misc/RelFinField.jl

Apparently the order must be swapped? Can you confirm @fieker?
```Julia
julia> f, o = FiniteField(7, 2, "o");
julia> fx, x = f["x"];
julia> F, u = FiniteField(x^3 + o + 4, "u");
julia> c = 3*u + 5*o + 1;
julia> norm(c)
x.data = 3*x + 5*o + 1
defining_polynomial(parent(x)) = x^3 + o + 4
resultant(x.data, defining_polynomial(parent(x))) = 5*o
5*o
julia> c^(divexact(7^6 - 1, 7^2 - 1))
2*o
```

Fix norm for relative finite fields

---

src/GrpAb/GrpAbFinGen.jl

This requires some thought:
- `==` takes the lattice into account, thus will not work with objectid
- just because groups are isomorphic (same snf) does not render them equal
- `snf` is (cometimes) slow...

rfc: hashing for abelian groups?

---

src/LocalField/Conjugates.jl
src/NumField/NfAbs/MPolyAbsFact.jl

Before:
```julia
julia> matrix(F, [[0, 0], [1, 0]])
[0   0]
[1   0]
julia> matrix([[F(0), F(0)], [F(1), F(0)]])
[0   1]
[0   0]
```
@fieker: This was only used in the conjugate code for local fields and some factorization code. I believe the GModule code in Oscar is also using it wrongly (this is how I found it).

Make matrix(::Vector{Vector{}}) return the correct matrix

---

src/Map/Map.jl
src/Map/MapType.jl

`show` is not supposed to include that trailing newline; having it causes extra newlines to be printed. E.g. from some Oscar examples:
```
julia> homogeneous_component(H, D[0])
(H_[0] of dim 2, Map from
H_[0] of dim 2 to H defined by a julia-function with inverse
)
julia>
```

Don't print trailing newline in show method for maps

---

src/Hecke.jl

Don't assume data is stored in `G.other`. Otherwise this will
break if we rename that member.

Avoid implementation detail of hasspecial / get_special

---

src/NumField/NfAbs/NfAbs.jl
test/NfAbs/NfAbs.jl

- Deal with the case that either going up or down does not suffice.
(For example, write a 3rd root of unity in the 9th cyclotomic field as an element of the 15th cyclotomic field.)
Most of the old code is still there, it has just been rearranged because we have to coerce first down and then up in the general case.
- Added tests for the situations that can occur.
- Removed code for the special case `isodd(fa) && (2*fa) % fb == 0` because it was wrong in some cases (see the extended tests).
- Return `nothing` if no coercion is possible and `throw_error` is not `Val{true}`; up to now, `false` was returned in one case.

attempt to fix `force_coerce_cyclo`

---

src/NumField/NfAbs/NfAbs.jl
test/NfAbs/NfAbs.jl

two small improvements w.r.t. PR #473:
- removed code lines that cannot be reached
- added tests for the case `throw_error == Val{false}`

changes suggested by the coverage report of PR #473

---

examples/NfMat.jl

more a proof-of-concept, the idea is to avoid the GC
by hiding the entries in the matrix and having a finalizer for
the matrix only.
rref! and ref! is working and competitive
view, hcat, vcat: OK
conversion to and from the classical type: OK
missing:
- native add, mul, ...
- det
all(?) generic methods should work - but without any benefit

add a "native" type for matrices over number fields

---

docs/src/function_fields/basics.md
docs/src/function_fields/elements.md

These link forms have been deprecated in Documented for a long time now

Don't link to 'latest' versions of docs

---

.github/workflows/CI.yml
.github/workflows/CILong.yml

v1 will be disabled February 1, 2022; see https://github.com/codecov/codecov-action

CI: update codecov/codecov-action to v2

---

src/QuadForm/Quad/Genus.jl

Seems to be superseeded by
`_representatives_for_equivalence_and_witt`

remove _representatives_for_equivalence

---

src/Map/automorphisms.jl
src/QuadForm/Herm/Genus.jl
src/QuadForm/Herm/Lattices.jl
src/QuadForm/Herm/Spaces.jl
src/QuadForm/Herm/Types.jl
src/QuadForm/Misc.jl
test/Map/NumField.jl
test/QuadForm/Herm/Spaces.jl

Up to now, we get the involution of a quadratic extension only via a `HermLat` or a `HermSpace`. I made available directly for any quadratic extensions and uses this function to create the involutions associated to `HermLat` and `HermSpace`. It seems to be more intuitive to get the involution directly from the field.

Added involution for quadratic extensions

---

src/Misc/Matrix.jl

isupper_triangular should check matrix M row i only up to min(i-1,ncols(M)), not max(i-1, ncols(M)) which would be until the end of the row for small i. (bug found while debbuging pAdicSolver with Avi)

Fix: isupper_triangular

---

src/QuadForm/Herm/Genus.jl
src/QuadForm/Herm/Mass.jl
src/QuadForm/Herm/Spaces.jl
src/QuadForm/Spaces.jl
test/QuadForm/Herm/Spaces.jl
test/QuadForm/Quad/Spaces.jl

There is still a `_isdefinite(V::AbsSpace)`, I don't know whether or not it has to stay or if we can remove it regarding that we have the other functions below... seems to be a function created before `istotally_positive` and `istotally_negative`. Yet, this first one return -1, 0 or 1, instead of boolean, so maybe it has a purpose somewhere. I don't know.

Fix definitness + tests for HermSpace

---

src/AlgAss/Types.jl
src/AlgAssAbsOrd/Types.jl
src/Hecke.jl
src/HeckeTypes.jl
src/Misc/OrdLocalization.jl

This contains PR #567 plus one extra commit. The extra commit uses `get_cached!` in a few more places where it seems sensible; but this time around, semantics change: the old code always tried to get data from the cache, even if `cached` was set to `false`. The new code uses `get_cached!`, and hence will never access the cache when `cached == false`.
I cannot judge whether this is change is OK, or not. If it is not OK, then I suggest that besides closing this PR, also a few comments are added to state explicitly why the behavior is different.

Use `get_cached!` some more, changing semantics a bit

---

src/Hecke.jl
src/HeckeTypes.jl

This `FacElemMon{AnticNumberField}` constructor is a bit weird. It seems to override the default caching strategy (where `FacElemMonDict` is used to store the cached object) by one where the data is instead stored as an attribute of the given `AnticNumberField`. But it still *also* checks if the required object already exists in `AnticNumberField`...
But the key used is the ring itself, so how could `haskey(FacElemMonDict, R)` ever return `true`? I am tempted to just remove that check
Independently, I wonder: why bother overriding the cache at all in this special case? My guess: because the global `FacElemMonDict` really is a leak. But then perhaps this special case should be extended to all rings that support attribute storage (which we nowadays can check using …

Remove _get_fac_elem_mon_of_nf

---

src/NumFieldOrd/NfOrd/Ideal/Prime.jl

Completely untested, but `subgroup` does not seem to be defined anywhere? Perhaps I missed something, or perhaps these functions are simply not covered by CI?
Motivated by https://github.com/oscar-system/Oscar.jl/issues/667﻿

Replace subgroup by sub

---

src/Map/MapType.jl

An example where this extension turns out to be useful is shown in the comments in oscar-system/Oscar.jl/pull/1067.

admit also types instead of functions in `MapFromFunc`

---

src/QuadForm/Herm/Mass.jl
src/QuadForm/Herm/Spaces.jl
src/QuadForm/Lattices.jl
test/QuadForm.jl
test/QuadForm/Genus.jl
test/QuadForm/Herm.jl
test/QuadForm/Herm/Genus.jl
test/QuadForm/Herm/GenusRep.jl
test/QuadForm/Herm/Mass.jl
test/QuadForm/Herm/Spaces.jl
test/QuadForm/Lattices.jl

I have fixed the code for the mass of hermitian lattices and I have implemented the use of the automorphism group of definite lattices when it could be used. I have moved some tests to centralise as much as possible into the `~/test/QuadForm/Herm` directory. There were also few fixes to do in `~/Herm/Spaces.jl` that I have done. There is also more documentation where I could provide some.

Fix `mass` for `HermLat` and allow `use_auto`

---

src/NumField/NfAbs/NonSimple.jl
src/NumField/NfRel/NfRelNS.jl
src/Sparse/Matrix.jl
src/Sparse/Rref.jl
src/Sparse/Solve.jl
test/Sparse.jl
test/Sparse/Solve.jl

Implements `can_solve_with_solution(::SMat, SMat)` by basically copying the function for dense matrices from AbstractAlgebra.
I noticed that there already is a `can_solve_with_solution(::SMat, ::SRow)` which uses `echelon!` for the row reduction instead of the new `rref`. I made this function also work with `SMat` in the second argument and renamed it to `_can_solve_with_solution`. I have the impression that my new functions are faster, see the timings below (this is also the case for my actual application in invariant theory).
```
julia> for i = 6:10
r = 10*i
c = r + 10
M = matrix(GF(5), rand([0,0,0,0,0,0,0,0,0,0,1], r, c))
Ms = sparse_matrix(M)
N = matrix(GF(5), rand([0,0,0,0,0,0,0,0,0,0,1], r, 1))
Ns = sparse_matrix(N)
@btime can_solve_with_solution(Ms, Ns, side = :right)
@btime …
```

Sparse linear system solving

---

src/AlgAssAbsOrd/Conjugacy/Husert.jl
src/Misc/jordan.jl
test/Misc/jordan_test.jl

I needed common eigenspaces and noticed that Hecke has them (well hidden). Now they work again (`intersect_spaces` -> `_intersect_spaces`).
I decided that the default side for an eigenspace should be `:right` to be consistent with `kernel` (which is also an eigenspace after all).

Fix common_eigenspaces

---

src/Misc/Integer.jl
test/Misc/Integer.jl

I like ranges 😊 Especially for test and demonstration purposes. So, I was puzzled, when the current stub produced wrong results (for step ranges with `step ≠ 0`) and `MethodError`s, so I fixed this for some the tests I came up with.
Though I did not want to copy half of Julia’s range implementation. So exotic use cases may still throw some `MethodError` but at least hopefully no wrong results. Also sadly `fmpz(1) .* (fmpz(1):fmpz(2)) isa StepRangeLen{fmpz, fmpz, fmpz, BigInt}` resulting in mixed `fmpz` and `BigInt` comparisons on further use. This could be fixed, but it’s probably not worth the effort, regarding that no one else seemed to miss ranges at all 😄
I guess, `fmpz` ranges could also be migrated to Nemo instead?

Implement `fmpz` unit ranges

---

src/NumField/NfAbs/Elem.jl
src/NumField/NfAbs/PolyFact.jl
src/NumField/SimpleNumField/Subfields.jl
test/NfAbs/Subfields.jl
test/NumField/Elem.jl

- inplace setprec! for qadics (or polys over qadic) was no longer
working. (HenselCtxQadic)
Unnotices as this is not used (any more) in factoring
but is used in galois
- princial_subfields in relative extension was broken

minor fixes for galois group over number field

---

docs/Build.jl
docs/mkdocs.yml
docs/src/quad_forms/basics.md
docs/src/quad_forms/genusherm.md
docs/src/quad_forms/introduction.md
docs/src/quad_forms/lattices.md
src/HeckeTypes.jl
src/Map/Map.jl
src/Map/NfRel.jl
src/Map/NfRelOrd.jl
src/Misc/Poly.jl
src/Misc/RelFiniteField.jl
src/NumField/NfRel/Types.jl
src/NumFieldOrd/NfOrd/ResidueField.jl
src/QuadForm/Herm/Genus.jl
src/QuadForm/Herm/Lattices.jl
src/QuadForm/Herm/LocallyIsometricSublattice.jl
src/QuadForm/Herm/Spaces.jl
src/QuadForm/Lattices.jl
src/QuadForm/Quad/Lattices.jl
src/QuadForm/Quad/Spaces.jl
src/QuadForm/Spaces.jl
test/NumFieldOrd/NumFieldOrd.jl

This follows #639. I have adapted some similar codes written for absolute residue field. I had to modify some other methods, like the `(pre)image(::Map{C, D},a)` because for the map to residue fields, there are more than 2 parameters. I could only produce examples in tower of 3 extensions at most.

add `relative_residue_field` for `NfRel`

---

src/EllCrv/EllCrv.jl
src/EllCrv/MordellWeilRank.jl

- Speedup the computation in the hot loop using inplace operations
- Avoid rational arithmetic (everything is integral)
@JHanselman Can you have a look and confirm that this makes sense?
P.S.: For `E1` the time goes down from 15s to 0.4s on my machine.

Some improvments for the Mordell-Weil group things

---

docs/src/number_fields/fields.md
src/AlgAss/AlgGrp.jl
src/AlgAssAbsOrd/ICM.jl
src/AlgAssAbsOrd/PIP.jl
src/Grp/Morphisms.jl
src/NumField/NfAbs/NfAbs.jl
src/NumField/NfRel/NfRel.jl
src/NumField/NonSimpleNumField/Field.jl
src/NumField/SimpleNumField/Field.jl
test/AlgAss/AlgAss.jl
test/AlgAssAbsOrd/ICM.jl
test/FieldFactory/FrobeniusExtensions.jl
test/Misc/NumberField.jl
test/NfAbs/NonSimple.jl
test/NfAbs/Simplify.jl
test/NfAbs/Subfields.jl
test/NfOrd/NarrowPicardGroup.jl
test/NfRel/NfRel.jl
test/NfRel/NfRelOrd.jl
test/NumField/CM.jl
test/NumField/Elem.jl
test/NumField/NfAbs/NfAbs.jl
test/NumField/NfRel/Simplify.jl
test/RCF/rcf.jl

The function `is_isomorphic` just returns a `Bool`, while `is_isomorphic_with_map` also returns a map.
This brings us in line with what we do in Oscar now (modulo the underscore after `is`, but that's temporary). Also, before this PR, some `isisomorphic` methods had one return value, some had two, which was quite confusing.
Breaking change.
Contains PR #682 which ideally should be merged first.

Rename `isisomorphic` -> `is_isomorphic`, add `is_isomorphic_with_map`

---

src/GrpAb/ChainComplex.jl

I'm not sure, but I think also `getindex` for cochain complexes is wrong.

Fix map indexing for cochain complexes

---

src/NumField/NfRel/NfRel.jl

One "over" seems to be superfluous.

changed `show` method for relative number fields

---

src/QuadForm/Torsion.jl
test/QuadForm/Torsion.jl

Adding iterators for `TorQuadmod`, based on the iterator of the underlying abelian group.

Iterator for `TorQuadMod`

---

src/QuadForm/IO.jl
test/QuadForm/IO.jl

Add conversions to parseble Magma and Sage codes for `ZLat`. 
Minor fix on the Hecke one: one entry argument was missing (while useless in this case... is it necessary though for `HermLat` and `QuadLat` ?)

`ZLat` to Magma/Sage

---

src/QuadForm/Misc.jl
src/QuadForm/Spaces.jl
test/QuadForm/Lattices.jl

Needed a way to access the domain and codomain of the map from `restrict_scalars` for `AbsSpace`. Seemed that the type `VecSpaceRes` was not seen as a subtype of `HeckeMap`, so it had no header. I made this change, and modify the functions accordingly to match the new caching.

`VecSpaceRes` as `HeckeMap`

---

.github/workflows/CI.yml
.github/workflows/CILong.yml
.github/workflows/oscar.yml

GitHub warns that this is needed because they are updating from Node 12 to 16

CI: update some actions to latest versions

---

src/GrpAb/Elem.jl
test/GrpAb/Elem.jl

A small change to allow this:
```
julia> G = abelian_group([3, 0]);
julia> N = matrix(FlintZZ, 2, 1, [ 1, 1 ]);
julia> G(N)
Element of
GrpAb: Z/3 x Z
with components [1 1]
```
Seems to me to be the easiest way to make the construction in https://github.com/oscar-system/Oscar.jl/blob/5c7916ed7831ef993ba108418151f01ff0f5c9f2/src/Rings/mpoly-graded.jl#L182 work (without having to write a separate function for `fmpz_mat` there).

Allow "column vectors" in the construction of group elements

---

src/Sparse/Solve.jl
test/Sparse/Solve.jl

I forgot to set the `nnz` of the solution, when I wrote `can_solve_with_solution` for sparse matrices. Sorry!

Correctly set `nnz` in `can_solve_with_solution`

---

src/QuadForm/Torsion.jl
test/QuadForm/Torsion.jl

In the case where the gram matrix of the quadratic form of the of the two is trivial, the case was not covered: actually it was returning an error because of the computation of the normal form. In this case, we can conclude before-hand looking at the moduli, the gram matrices and the underlying abelian groups.

Fix (anti)-isometry test for `TorQuadMod` is totally degenerate case

---

docs/src/quad_forms/basics.md
docs/src/quad_forms/lattices.md
src/QuadForm/Lattices.jl
src/QuadForm/Spaces.jl
test/QuadForm/Lattices.jl

This is an implementation of intersection, saturation and orthogonal submodule for `HermLat` and `QuadLat`, using restriction of scalars. These work also in the case of non full-rank modules/pseudo-matrices.
This pull request shall replace the previously opened #857 .
I modified `orthogonal_complement` into `orthogonal_submodule` to fit with the function defined for `ZLat`... I hope the implementation does what it should do, @simonbrandhorst ?
At least the broken tests pass now.

Intersection, saturation and orthogonal submodule of `AbsLat`

---

.github/workflows/CI.yml
.github/workflows/CILong.yml

This should avoid some warnings in the GH Actions web view

CI: update codecov/codecov-action to latest version

---

src/QuadForm/Quad/ZLattices.jl
src/QuadForm/Spaces.jl
src/QuadForm/Torsion.jl
test/QuadForm/Torsion.jl

I guess this should be here temporarily, until we decide what we exactly do with `orthogonal_sum`. Things is that I would need the part for `TorQuadMod` on Oscar. Since it can be made on Hecke and could be of general use, I decided to implement this here.
Ideally with this pattern, we could have 4 functions each time: one without maps, one with injections, one with projections and one with both.

Orthogonal sums with injections and projections

---

docs/src/quad_forms/basics.md
docs/src/quad_forms/discriminant_group.md
docs/src/quad_forms/integer_lattices.md
src/QuadForm/Quad/ZGenus.jl
src/QuadForm/Quad/ZLattices.jl
src/QuadForm/Spaces.jl
src/QuadForm/Torsion.jl
test/QuadForm/Quad/Spaces.jl
test/QuadForm/Quad/ZLattices.jl
test/QuadForm/Torsion.jl

In order to access for `ZLat`, `QuadSpace` (for now, should be extended to `HermSpace`, `QuadLat` and `HermLat` when needed) and `TorQuadMod` to multiple orthogonal sums with the corresponding injections and projections (we are in nice categories), we add the alias `direct_sum`. It is close to the similar function for abelian groups.

`direct_sum` as an alias for `_orthogonal_sum_with_...`

---

src/HeckeTypes.jl
src/NumFieldOrd/NfOrd/FacElem.jl

The assignment `z.conj_log_cache = ...` is lowered to a call to `setproperty!(::FacElemMon{AnticNumberField}, ::Symbol, ::Dict{RingElem, Vector{arb}})` and this ultimately was the source of an invalidation when Singular.jl got loaded. We now avoid this by passing the new dicts directly as arguments to `new`.
In the `FacElemMon{S}` there also was a bug in that it used `Dict{Int, Dict{nf_elem, arb}}`, i.e. with `arb` instead of `Vector{arb}`. The same issue was also present in `_conjugates_arb_log`. I ended up rewriting the latter using `get!` to make it much simpler.
Before (with improved CxxWrap, not yet released;  in Julia 1.10-DEV on my M1 MacBook Pro):
```
julia> using Hecke, Singular; @time @eval maximal_order(quadratic_field(-3)[1]);
...
1.354915 seconds (1.27 M allocations: 84.366 …
```

Fix invalidations in FacElemMon constructor

---

src/LocalField/Elem.jl
test/LocalField/LocalField.jl

Alternatively, we could let this case be handled by `_log_one_units`.

Fix log(one(K)) for local fields

---

src/QuadForm/Torsion.jl
test/QuadForm/Torsion.jl

We cover the last case which was not covered by the previous algorithms, namely isometry test between two `TorQuadMod` which are not semi-regular and which do not split their respective radical quadratic. It uses partial isometries.

Isometry between `TorQuadMod`'s in the non split degenerate case

---

src/QuadForm/Quad/NormalForm.jl
src/QuadForm/Torsion.jl
test/QuadForm/Torsion.jl

Some time ago I thought I was clever and set the precision lower than I did in sage. Turns out I am not that clever.

fix precision issue in normal form

---

src/QuadForm/Quad/ZGenus.jl
test/QuadForm/Quad/ZGenus.jl

A missing corner case on genus comparison.

Fix comparison test `ZGenus`

---

src/LocalField/neq.jl

this is badly (=wrong) in the source paper, but correct in the acompanying code...

keep the basis property

---

docs/src/quad_forms/basics.md
src/QuadForm/Spaces.jl

@StevellM FIY: The version `Vararg{<:Bla}` is deprecated (and it is the same as `Vararg{Bla}` anyway).

Fix Vararg type

---

.github/workflows/CI.yml

The same as https://github.com/oscar-system/Oscar.jl/pull/1957, i.e. the tests should now fail once a deprecation warning is encountered.
cc @thofma @fieker @fingolfin

Fail CI on deprecation warning

---

src/Sparse/Matrix.jl

Before:
julia> zero_matrix(SMat, FlintZZ, 3, 4)
Sparse 3 x 4 matrix with 0 non-zero entries
julia>
After:
julia> zero_matrix(SMat, FlintZZ, 3, 4)
Sparse 3 x 4 matrix with 0 non-zero entries
julia>

Avoid redundant newline when showing SMat

---

docs/src/sparse/intro.md
src/Sparse/Matrix.jl
test/Sparse/Matrix.jl

I discussed with @HechtiDerLachs today how to create sparse matrices, and it took us a bit to determine that we should use `zero_matrix(SMat,R,n,m)` to specify an initial column count (i.e., we used `n=0` and set `m` to the final column count).
We both expected `sparse_matrix` to allow us to specify a row and/or column count. Based on this, my suggestion was to just add that. Instead of writing an issue, here is a proof of concept. If this is deemed acceptable, I can finish it up by linking the new constructor into the manual and adding a test.

Add `sparse_matrix(R,n,m)` as alternative to zero_matrix(SMat,R,n,m)

---

docs/src/quad_forms/Zgenera.md
docs/src/quad_forms/basics.md
docs/src/quad_forms/discriminant_group.md
docs/src/quad_forms/genusherm.md
docs/src/quad_forms/integer_lattices.md
docs/src/quad_forms/lattices.md
src/NumFieldOrd/NfOrd/LLLctx.jl
src/QuadForm/Database.jl
src/QuadForm/Herm/Genus.jl
src/QuadForm/Herm/GenusRep.jl
src/QuadForm/Herm/Types.jl
src/QuadForm/IO.jl
src/QuadForm/Lattices.jl
src/QuadForm/Quad/Genus.jl
src/QuadForm/Quad/Types.jl
src/QuadForm/Quad/ZGenus.jl
src/QuadForm/Quad/ZLattices.jl
src/QuadForm/Spaces.jl
src/QuadForm/Torsion.jl
src/QuadForm/Types.jl
test/QuadForm/Genus.jl
test/QuadForm/Herm/Genus.jl
test/QuadForm/Quad/Genus.jl
test/QuadForm/Quad/GenusRep.jl
test/QuadForm/Quad/ZGenus.jl
test/QuadForm/Quad/ZLattices.jl
test/QuadForm/Torsion.jl
test/QuadForm/indefiniteLLL.jl

Renamings done:
- `AbsSpace` -> `AbstractSpace` (`Abs` is reserved for `Absolute`)
- `AbsSpaceMor` -> `AbstractSpaceMor` (same as above)
- `AbsLat` -> `AbstractLat` (same as above)
- `TorQuadMod` -> `TorQuadModule` (modules are called `Module`)
- `TorQuadModElem` -> `TorQuadModuleElem` (same as above)
- `TorQuadModMor` -> `TorQuadModuleMor` (same as above)
- `LatticeDB` -> `LatDB` (lattices defined as `Lat` except group lattices (which are not the same kind of lattices))
- `NfLattice` -> `NfLat` (same as above)
Some other renamings for genera, in order to have something consistent. I chose `ZGenus` as a standard, and so:
- `genera` -> `Zgenera` ( the enumeration function)
- `GenusHerm` -> `HermGenus` (since it is a genus, we put `Genus` at the end)
- `LocalGenusHerm` -> `HermLocalGenus` …

Some renamings

---

src/ModAlgAss/Morphisms.jl

The `morphism` function for `ModAlgAss` just did not work due to `M` erroneously being called `matrix`:
```julia
m1 = matrix(QQ, [1;;])
M1 = Amodule([m1])
Hecke.morphism(M1, M1, m1)
```
results in
ERROR: MethodError: no method matching *(::QQMatrix, ::typeof(matrix))

Fix variable name in `morphism` of `ModAlgAss`

---

src/Hecke.jl
src/QuadForm/Quad/ZLattices.jl
src/QuadForm/Torsion.jl
test/QuadForm/Quad/ZLattices.jl
test/QuadForm/Torsion.jl

Some little things I have done on my local codes that could be done. I have removed the deprecated codes which are not used anymore in Oscar, I have added some documentation and an export.
I have added `coinvariant_lattice` to go along with `invariant_lattice` and the possibility to check whether a `TorQuadModuleElem` has a preimage along a `TorQuadModuleMor` (a `has_preimage` function)

Miscellaneous

---

src/HeckeTypes.jl
src/LinearAlgebra/Solve.jl
src/NumFieldOrd/NfOrd/Ideal/Prime.jl
src/Sparse/Matrix.jl

This minimizes overhead from them and also allows us to remove
the caches as instances can be stack allocated.

Turn MatSpace from mutable struct to struct

---

src/QuadForm.jl
src/QuadForm/Herm/Genus.jl
src/QuadForm/IO.jl
src/QuadForm/Misc.jl
test/QuadForm/Herm/Genus.jl

This was a piece of code which I guess was not triggered by the tests we currently had.
At first it was suppose to be a fix for `representative`, but the example I had is taking forever, so I just restricted to computing the middle step which was bugged (to avoid to have a test running for 20min because of the computation of a maximal integral lattice)
For help I have added another `to_hecke` function for `HermGenus`.

Fix generic `_hermitian_form_with_invariants`

---

src/QuadForm/Quad/ZLattices.jl
test/QuadForm/Quad/ZLattices.jl

Calling the function `ZLattice` was made by assuming that the entry matrix was actually a basis matrix, without checking it. Now it is always checked by default, but we leave the optional arguments `isbasis` and `check` for internal use.
There were few other places where the entry matrix was not always a basis so I have modified the functions accordingly (namely `lattice_in_same_ambient_space`, `is_primitive` and multiplication of a lattice by a scalar).
Then to avoid checking arguments in functions for which we know what is happening, I have disabled the input checks.

Fix input checks for creation of `ZLat`

---

docs/src/abelian/structural.md
docs/src/class_fields/intro.md
docs/src/sparse/intro.md

Some math mode content was not put inside `$...$` but other fences. As a result the generated documentation showed something wrong.

Fix some LaTeX code fences

---

src/GrpAb/Map.jl
src/QuadForm/Torsion.jl
src/QuadForm/Types.jl
test/QuadForm/Torsion.jl

- Add accessors to underlying abelian group homomorphism and the associated matrix
- Add `id` for `TorQuadModule`, parallel to the existing method for `GrpAbFinGen`
- Add `kernel` for `TorQuadModuleMor`
- Add `trivial_map` and `zero` for zero maps between torsion quadratic modules
- Add arithmetic for `TorQuadModuleMor`
- Add multiple self composition for torsion quadratic modules endormorphism using `^`
- Add evaluation of polynomial with integral coefficients at torsion quadratic module endomorphisms

Add functionalities for `TorQuadModuleMor`

---

src/Misc/FiniteField.jl
test/Misc/FiniteField.jl

Resolves oscar-system/Oscar.jl#862.
This has to wait for corresponding changes in Nemo (nemocas/Nemo.jl#1444 and nemocas/Nemo.jl#1454).

Use `VarName` for GF constructors

---

src/Sparse/HNF.jl

https://docs.oscar-system.org/dev/Hecke/sparse/intro/ contains some functions that are not exported. This PR exports all of those, that are defined in `sparse/HNF.jl`.

Export some functions in `sparse/HNF.jl`

---

docs/src/quad_forms/Zgenera.md
docs/src/quad_forms/basics.md
docs/src/quad_forms/discriminant_group.md
docs/src/quad_forms/genusherm.md
docs/src/quad_forms/integer_lattices.md
docs/src/quad_forms/lattices.md
src/QuadForm/Herm/Genus.jl
src/QuadForm/Lattices.jl
src/QuadForm/Quad/ZGenus.jl
src/QuadForm/Quad/ZLattices.jl
src/QuadForm/ShortVectors.jl
src/QuadForm/Spaces.jl
src/QuadForm/Torsion.jl
src/QuadForm/Types.jl

I could not build the documentation locally, hopefully this will fix all the mistakes and bugs I have found in the html documentation for this section of the manual (the goal being to clear things up before next week summer school).

Fix (html) docs `QuadForm/`

---

docs/src/features/macros.md
src/Assertions.jl

Most uses of `@vprint` add a newline by providing `'\n'` at the end of the message string. This PR adds a dedicated macro for this.

Add `@vprintln`

---

src/QuadForm/Quad/Spaces.jl
test/QuadForm/Quad/Spaces.jl

This makes
```
inner_product(V, [1, 1], [1, 2])
```
work.

Make inner_product work for more input types

---

src/LocalField/neq.jl

by commenting out the `@show` statements.
Resolves https://github.com/oscar-system/Oscar.jl/issues/2446.

Make Oscar tests no longer noisy

---

src/QuadForm/Torsion.jl
test/QuadForm/Torsion.jl

According to the documentation (and what was planned at first), we only care about the underlying abelian group structure. So in fine, being degenerate or not is not mportant. I have some cases where I would be glad to detect the abelian group structure even in the degenerate case (for instance for gluings)

Remove unnecessary check

---

src/Misc/Poly.jl
test/Misc/Poly.jl

A `schur_index` computation failed for me, due to `n_positive_roots` failing if two roots are rather close by. This proposal simply doubles the precision in that case. See the added test for an example.

Increase precision to isolate roots in `n_positive_roots`

---

src/NumFieldOrd/NfOrd/LinearAlgebra.jl
src/NumFieldOrd/NfRelOrd/FracIdeal.jl
test/NfOrd/LinearAlgebra.jl

Fixes #1112 
The only meaningful change is the added row reduction in line 1389. I also added some comments (apparently I wasn't a big fan 6 years ago) and restructured the code a little bit.
Sorry for the wrong implementation.
I did not touch `is_pseudo_hnf`. It does not test whether the entries above the diagonal are reduced, but there is no documentation whether it should and it is an internal function any way.

Correctly reduce rows in `pseudo_hnf_kb`

---

src/NumField/CM.jl

Resolves https://github.com/oscar-system/Oscar.jl/issues/1741.

Fix printing of `0::acb`

---

src/AlgAss/AlgMat.jl

Verifying large multiplication tables needs lots of time. If we just created it from a matrix algebra, I see no need to check it.

Do not check multiplication table from matrix algebra

---

src/QuadForm/Quad/Spaces.jl
test/QuadForm/Quad/Spaces.jl

Typo in the code of `is_isotropic` for quadratic spaces. I have fixed and put an example from Cassels for which the previous implementation could return a wrong output (I have checked it by hand, following Cassels propositions)

Fix `is_isotropic`

---

src/QuadForm/Quad/ZLattices.jl
src/QuadForm/indefiniteLLL.jl
test/QuadForm/indefiniteLLL.jl

There was a conflict of conventions between PARI left actions and our right actions, so at that time the code was written with a bunch of unnecessary `transpose`. This PR is about fixing this problem, as well as turning the files related to `indefiniteLLL` to a format similar to other files in the repo.

Cleanup `indefiniteLLL`

---

docs/src/quad_forms/Zgenera.md
src/Aliases.jl
src/Deprecations.jl
src/QuadForm/Quad/Types.jl
src/QuadForm/Quad/ZGenus.jl
src/QuadForm/Torsion.jl
test/QuadForm/Quad/ZGenus.jl

Some weeks ago, I have continued the big renaming within `QuadForm/` and I renamed `ZpGenus` to `LocalZZGenus`. But the latter was actually inconsistent with `HermLocalGenus` and `QuadLocalGenus` used for the other lattices ( and inconsistent with the new naming conventions). I have therefore changed it to the appropriate form `ZZLocalGenus`. 
I have checked and there are no occurrences of this type in the master of Oscar so it should not break it.

Fix renaming of local genera for integer lattices

---

src/Misc/Matrix.jl

Allow singular matrices in `saturate`

---

src/AlgAss/AlgMat.jl
src/AlgAss/AlgMatElem.jl
test/AlgAss/AlgMat.jl

This mostly improves the case of matrix algebras with small dimension `d=dim(A)` compared to the dimension `D=degree(A)^2*dim_of_coefficient_ring(A)` of the full matrix algebra.
This improves `coefficients(B[i]*B[j])` by exploiting, that we know `B[i]*B[j]` to be representable as linear combination of the $d$ entries of `B`. The old code in `_check_matrix_in_algebra` does a $D×D$ basis transform of our element `B[i]*B[j]`, checking, that it is then really spanned by the first $d$ unit vectors. The new `_matrix_in_algebra`  just transforms the $d$ pivot columns without a check.
This gave slight speedup in the full matrix algebra case (if one disables the late #1130 special handling) and tenfold and more, when $D÷d$ gets larger.
Probably, the `_check_matrix_in_algebra` code could also …

Speed up `multiplication_table(::AlgMat)`

---

src/AlgAss/AlgAss.jl
src/AlgAss/AlgMat.jl
src/AlgAss/AlgMatElem.jl
test/AlgAss/AlgAss.jl

Concept for an alternative to #1133.

Use `associative_algebra` as frontend to `AlgAss` and disable checks when calling `AlgAss` directly

---

src/Hecke.jl

It is available in Nemo since [v0.27.0](https://github.com/Nemocas/Nemo.jl/releases/tag/v0.27.0).
Furthermore removed a duplicate entry in `exclude`.

Simplify `IntegerUnion` import

---

src/Misc/Matrix.jl

The call to `hnf(A)` gives a row echelon form, but no information about rank or pivots. These fast methods provide that information. (Without verifying the echelon form.)
Also fix the `transpose!` method, I have lately introduced.

Miscellaneous matrix methods

---

src/LinearAlgebra/Howell.jl
src/Map/FqPolyRing.jl
src/Misc/Integer.jl
src/Misc/Matrix.jl
src/Misc/Poly.jl
src/Misc/UnitsModM.jl
src/NumFieldOrd/NfOrd/StrongEchelonForm.jl

Nemo's compat is fixed to at least 0.34. Thus all of these checks for old Nemo versions can be safely removed.

Remove code dependent on old Nemo versions

---

src/QuadForm/Torsion.jl

Downstream sibling PR to https://github.com/Nemocas/Nemo.jl/pull/1484.
This should fix all uses of `is_prime_power_with_data` in Hecke, after the Nemo-PR has been merged.

Change return argument order of `is_prime_power_with_data`

---

src/Misc/MSet.jl

Some small changes to `misc/MSet.jl`:
- prettifying some docstrings, fixing typos
- `IteratorSize`, `IteratorEltype` and `eltype` now only implement the one dispatch taking a type. The other dispatches (for objects) are defined in julia base.
- `push!`, `pop!`, `delete!` and `multiplicity` now use the same ad-hoc coercion for the input
- export `multiplicity`
- add `filter`

Refactoring parts of `MSet.jl`

---

src/GrpAb/ChainComplex.jl

- all directions of all arrows in printing are reversed
- different printing for free_res and repsentations
- the fun!
(needs to be supplemented by an Oscar pr to
- use the new stuff
- fix the doctests )

fix (change) printing of complexes

---

src/Hecke.jl
test/setup.jl

allow Hecke.test_module("bla", false) again

---

src/EllCrv/EllCrv.jl
test/EllCrv/EllCrv.jl

Add Simon's constructor for elliptic curves.

---

src/QuadForm/Lattices.jl
src/QuadForm/Torsion.jl

The methods for (anti)-isometry creates type instability in Oscar, because of the `compose` methods: see my `@code_warntype` output
```
%168 = Oscar.is_anti_isometric_with_anti_isometry(%165, %167)::Tuple{Bool, 
Union{AbstractAlgebra.Generic.CompositeMap{TorQuadModule, 
TorQuadModule}, TorQuadModuleMor}}
```
We create thus a honest map instead of composing the functions.
I have also fixed some alignments.

Fix some type stability issue

---

docs/src/abelian/structural.md
src/GrpAb/GrpAbFinGen.jl

I do not see a deeper reason why not to. They are already used in Oscar for direct sums of modules and will be of use for Lie algebras in the near future.

Export `canonical_{in/pro}jection`

---

src/GenOrd/Ideal.jl
src/NumField/NfRel/NfRel.jl

This removes the code mentioned in https://github.com/thofma/Hecke.jl/issues/1145 to see where it is currently used aka what fails without it.
Resolves #1145.

Remove wildly general `check_parent`

---

Project.toml
src/AlgAss/AlgMat.jl
src/AlgAss/Types.jl
src/AlgAssAbsOrd/Ideal.jl
src/AlgAssAbsOrd/Order.jl
src/AlgAssAbsOrd/Types.jl
src/AlgAssRelOrd/Types.jl

Fixes https://github.com/thofma/Hecke.jl/issues/1139.
Let's see if anything breaks. If not, I see no reason not to change this.
However, I would classify this a breaking change.

Let `AbsAlgAss` no longer be a `Ring`

---

src/QuadForm/Lattices.jl
test/QuadForm/Lattices.jl

Fix trace equivalence for infinite isometries

---

src/Map/MapType.jl
src/Map/NfRelOrd.jl
src/QuadForm/Herm/LocallyIsometricSublattice.jl
src/QuadForm/Lattices.jl

Several changes deal with JET warnings about "captured variables"
resulting in disabled optimizations resp. type unstable code.
E.g. `mFF` was assigned different values in two places which then
are referenced inside closures.
Likewise, `NN` was used in lambdas, which we now avoid.

Add some tweaks for type stability etc.

---

docs/src/sparse/intro.md
src/NumField/NfRel/NfRelNS.jl
src/Sparse.jl
src/Sparse/Matrix.jl
src/Sparse/Row.jl
src/Sparse/Solve.jl
test/Sparse/Matrix.jl
test/Sparse/Row.jl
test/Sparse/Solve.jl

Changes:
1. Add `can_solve` by only doing parts of `can_solve_with_solution`
2. Adapt `Matrix(::SMat)` and `Array(::SMat)` to their docstrings (and move them to the same place). This changed them from returning a AA MatElem to a julia Matrix.
3. Add a similar function `Vector(::SRow)`
4. Copy the `SRow` <-> `MatElem` conversion from Oscar here. This can then be deleted afterwards in Oscar.
5. Allow scalar multiplication from left and from right, and widen signature.
One could consider 2 above breaking, but I would instead call that a bugfix, as the intended behaviour described in the docstring didn't change.
It would be great if I could get a release shortly after merging this to be able to use it in Oscar.LieAlgebras.

More functionality for sparse matrices and rows

---

src/Sparse/Matrix.jl
test/Sparse/Matrix.jl

The following example fails:
```julia
A = sparse_matrix(FlintZZ, [2 0; 0 0])
kronecker_product(A, A)
```
I would expect it to instead return the sparse matrix `[4 0 0 0; 0 0 0 0; 0 0 0 0; 0 0 0 0]`.

Fix `kronecker_product` for sparse matrices with zero row

---

Project.toml
examples/Plesken.jl
src/EllCrv/Finite.jl
src/GenOrd/Ideal.jl
src/LocalField/LocalField.jl
src/LocalField/qAdic.jl
src/Misc/Plesken.jl
src/Misc/Poly.jl
src/Misc/RelFiniteField.jl
src/NumField/NfAbs/Simplify.jl
src/NumFieldOrd/NfOrd/Hensel.jl
src/NumFieldOrd/NfOrd/Ideal/Prime.jl
src/NumFieldOrd/NfOrd/MaxOrd/Polygons.jl
src/QuadForm/Quad/NormalForm.jl
test/AlgAss/AlgAss.jl
test/EllCrv/Finite.jl
test/EllCrv/Isogeny.jl
test/GenOrd/MaximalOrder.jl
test/Misc/FiniteField.jl
test/Misc/Poly.jl
test/Misc/RelFinField.jl
test/Misc/meataxe.jl
test/Misc/stable_subgroups.jl
test/QuadForm/Quad/PadicLift.jl

Command used to create this PR:
git grep -l -w FiniteField | xargs perl -pi -e 's;\bFiniteField\b;finite_field;g'

Switch from FiniteField to finite_field

---

src/GenOrd/Auxiliary.jl

... for RationalFunctionField. It was neither used nor exported.
Soon we will have the real thing, see https://github.com/Nemocas/AbstractAlgebra.jl/pull/1463

Remove rational_function_field wrapper

---

test/QuadForm/Quad/Spaces.jl

I don't see what purposes these tests are meant to serve. Also they lead to a warning ("WARNING: Method definition change_base_ring ... overwritten ..."), and potentially change the behavior of later tests.
Resolves #1235
@thofma added this in PR #139.

Remove unnecessary tests

---

src/Deprecations.jl
src/FunField/Divisor.jl

A quick search shows that `field_of_fractions` isn't used anywhere, but causes confusion with `fraction_field` used in OSCAR and co.
I am not sure if simply removing or offering `fraction_field` as an alias of `function_field` is better. For now I think it is best to deprecate `field_of_fractions`.

deprecate `field_of_fractions(O::GenOrd)`

---

docs/src/function_fields/degree_localization.md
src/FunField/DegreeLocalization.jl

I found it while trying to get https://github.com/oscar-system/Oscar.jl/pull/2922 working.

Fix some mathmode in docu

---

src/NumFieldOrd/NfOrd/Clgp/Proof.jl

This line was failing for me when I tried to compute class groups with GRH=false

remove unneeded broken line in class group proof

---

examples/Klueners.jl
examples/MultiQuad.jl
examples/Round2.jl
examples/polymake.jl
src/AlgAssAbsOrd/LocallyFreeClassGroup.jl
src/GenOrd/GenOrd.jl
src/GenOrd/Ideal.jl
src/GenOrd/Types.jl
src/GrpAb/GrpAbFinGen.jl
src/GrpAb/Map.jl
src/GrpAb/stable_sub.jl
src/LocalField/neq.jl
src/Map/GrpAb.jl
src/Misc/Poly.jl
src/Misc/PseudoPolynomial.jl
src/NumField/NfAbs/MPolyAbsFact.jl
src/NumFieldOrd/NfOrd/LinearAlgebra.jl
src/NumFieldOrd/NfOrd/norm_eqn.jl

To prepare for https://github.com/Nemocas/AbstractAlgebra.jl/pull/1467

Remove many calls to `*cat(::Vector{...})`

---

src/NumField/NfAbs/NonSimple.jl

Example:
```
R,x=polynomial_ring(QQ)
K,_=number_field([x])
absolute_simple_field(K)
```

Fix typo in simple_extension(...)

---

src/NumField/NfAbs/NonSimple.jl
src/NumField/NfRel/Simplify.jl
test/NfAbs/NonSimple.jl
test/NumField/NfRel/Simplify.jl

Fixes for trivial non-simple fields

---

docs/src/quad_forms/Zgenera.md
src/QuadForm/Herm/Genus.jl
src/QuadForm/Herm/Lattices.jl
src/QuadForm/Herm/Mass.jl
src/QuadForm/Herm/Spaces.jl
src/QuadForm/Lattices.jl
src/QuadForm/Misc.jl
src/QuadForm/Quad/GenusRep.jl
src/QuadForm/Quad/Lattices.jl
src/QuadForm/Quad/Spaces.jl
src/QuadForm/Quad/ZGenus.jl
src/QuadForm/Quad/ZLattices.jl
src/QuadForm/Spaces.jl
src/QuadForm/Torsion.jl

Mainly trying to avoid creation of lists when it is not necessary and use more the the `!` functions whenever possible. 
I have tried to improve some type stability by giving new names to variables which were changing types during the sub-processes and inferring more type for lists. Hopefully this with help for compilation time (?).
I have added some semi-colons and spaces in some places where I noticed then missing, for code readability: this was not my first goal so the code is not perfectly reformatted.

Attempt to improve some codes in `QuadForm`

---

Project.toml
src/Sparse/Matrix.jl
test/Sparse/Matrix.jl

Another nasty bug in that function. I added the example that confused me as a test.
I am looking forward to a fast merge and release of this so that I can use it in https://github.com/oscar-system/Oscar.jl/pull/2936.

Fix `kronecker_product(::SMat, ::SMat)`

---

docs/src/sparse/intro.md
src/Sparse/Matrix.jl
test/Sparse/Matrix.jl

This PR adds the following dispatches
```julia
dot(x::SRow{T}, A::SMat{T}, y::SRow{T}) where T
dot(x::MatrixElem{T}, A::SMat{T}, y::MatrixElem{T}) where T
dot(x::AbstractVector{T}, A::SMat{T}, y::AbstractVector{T}) where T
```
If you have any suggestions for improvements, let me know.

add `dot(x, A, y)` for sparse matrices

---

src/NumFieldOrd/NfOrd/NfOrd.jl

Sorry.
The failure in https://github.com/thofma/Hecke.jl/actions/runs/6700773309/job/18207222933?pr=1265 should not happen any more; I ran the test in `test/AlgAssAbsOrd/FakeAbsOrdRing.jl` for every possible `x`.

Fix stupid mistake

---

src/QuadForm/IO.jl

I was using `MagmaCall` to set up a Magma <-> Julia interaction to use Markus' code for hermitian lattices when I noticed that the big renaming had some unwanted side effects, for instance for our `to_magma` functions.

Revert unwanted renamings

---

src/QuadForm/Torsion.jl

The old code added a `convert(TorQuadModule, ret)` on the return
value of the attribute. The new code instead leads to a type
assertion, which is what we really want here.

Replace implicit 'convert' by attribute return type

---

src/QuadForm/LineOrbits.jl
src/QuadForm/Types.jl
test/QuadForm.jl
test/QuadForm/LineOrbits.jl

To prepare random Kneser's neighbour method, allow to have access to random lines from the `LineEnumCtx`. It might not be the most optimized way but at least it works.

Random lines in `LineEnumCtx`

---

src/Misc/jordan.jl
test/Misc/jordan_test.jl

Fix Jordan normal form

---

src/Map/NfOrd.jl
test/NfOrd/ResidueField.jl

Fix preimage map of residue field

---

src/QuadForm/Herm/Lattices.jl
src/QuadForm/Lattices.jl
src/QuadForm/Quad/Lattices.jl
src/QuadForm/Quad/ZLattices.jl

Fix and unify docs about maximal lattices

---

src/AlgAss/AlgMat.jl
src/AlgAss/AlgQuat.jl
src/AlgAssAbsOrd/Elem.jl
src/AlgAssAbsOrd/Ideal.jl
src/AlgAssAbsOrd/Order.jl
src/AlgAssRelOrd/Elem.jl
src/AlgAssRelOrd/Order.jl
src/EllCrv/EllCrv.jl
src/FunField/HessQR.jl
src/GenOrd/GenOrd.jl
src/Grp/GenGrp.jl
src/GrpAb/GrpAbFinGen.jl
src/HeckeTypes.jl
src/HypellCrv/HypellCrv.jl
src/LocalField/Elem.jl
src/LocalField/LocalField.jl
src/Map/NumField.jl
src/Map/NumberField.jl
src/Misc/RelFiniteField.jl
src/NumField/Embedded.jl
src/NumFieldOrd/NfOrd/FracIdeal.jl
src/NumFieldOrd/NfOrd/Ideal/Ideal.jl
src/NumFieldOrd/NfOrd/NfOrd.jl
src/NumFieldOrd/NfOrd/ResidueRing.jl
src/NumFieldOrd/NfRelOrd/NfRelOrd.jl
src/NumFieldOrd/NfRelOrd/OrdElem.jl
src/NumFieldOrd/NfRelOrd/ResidueRing.jl

As they already exist via https://github.com/Nemocas/AbstractAlgebra.jl/blob/9dd22199b5262f23ad071b877f5d4fb5ce9ad436/src/fundamental_interface.jl#L53 and are only inconsistently used throughout Hecke.
Furthermore, export `ideal_type`, so Oscar can use the same function for its methods.

Remove instance dispatches for `{elem,parent}_type`

---

examples/MultDep.jl
examples/Suri.jl
src/AlgAss/Elem.jl
src/AlgAssAbsOrd/Elem.jl
src/AlgAssAbsOrd/Ideal.jl
src/AlgAssRelOrd/Ideal.jl
src/Deprecations.jl
src/GrpAb/Dual.jl
src/LocalField/Elem.jl
src/LocalField/Poly.jl
src/LocalField/Ring.jl
src/NumField/NfRel/NfRel.jl
src/NumFieldOrd/NfOrd/Ideal/Arithmetic.jl
src/NumFieldOrd/NfRelOrd/FracIdeal.jl
src/NumFieldOrd/NfRelOrd/Ideal.jl
src/NumFieldOrd/NumFieldOrdElem.jl
src/QuadForm/QuadBin.jl
src/Sparse/Row.jl
test/NfOrd/Elem.jl

We need this in order to write generic code

Add missing 'check' argument to several divexact methods

---

src/AlgAss/AlgMat.jl

Previously, full matrix algebras were assumed to be not commutative. This PR changes this for degree-one matrix algebras.
As I found no tests for this function, I did not write any myself.

Fixes is_commutative for 1-dim matrix algebras

---

src/NumField/Hilbert.jl

Markus Kirschmer explained me how his code works, so I have added some comments related to this.
Now we have details about the process and why the output is what we want ( + some references for free)

Add comments on the implementation of local Hilbert symbols

---

test/Misc/Poly.jl

In https://github.com/Nemocas/Nemo.jl/pull/1596 `is_squarefree` was set to return `false` for 0. The Hecke tests wanted `true`.
(Which makes me wonder whether these tests should be in Nemo.)

Adjust to Nemo changes: 0 is not squarefree any more

---

src/QuadForm/Morphism.jl

Small optimization in automorphism computation

---

src/Sparse/Row.jl

before:
```julia
julia> (sparse_row(QQ), sparse_row(QQ))
(Sparse row with positions Int64[] and values QQFieldElem[]
, Sparse row with positions Int64[] and values QQFieldElem[]
)
julia> [sparse_row(QQ), sparse_row(QQ)]
2-element Vector{SRow{QQFieldElem, Vector{QQFieldElem}}}:
Sparse row with positions Int64[] and values QQFieldElem[]
Sparse row with positions Int64[] and values QQFieldElem[]
```
after:
```julia
julia> (sparse_row(QQ), sparse_row(QQ))
(Sparse row with positions Int64[] and values QQFieldElem[], Sparse row with positions Int64[] and values QQFieldElem[])
julia> [sparse_row(QQ), sparse_row(QQ)]
2-element Vector{SRow{QQFieldElem, Vector{QQFieldElem}}}:
Sparse row with positions Int64[] and values QQFieldElem[]
Sparse row with positions Int64[] and values QQFieldElem[]
```

Fix printing of SRow in compound structures

---

src/QuadForm/Quad/ZLattices.jl
test/QuadForm/Quad/ZLattices.jl

`root_sublattice` allowed odd root lattices but the recognition function did not. So I introduce the root lattice $I_1$ for odd lattices, which is just the odd (positive definite) unimodular lattice of rank 1.
@simonbrandhorst

Fix `root_lattice_recognition`

---

src/AlgAssAbsOrd/Ideal.jl
src/Grp/GenGrp.jl
src/GrpAb/Lattice.jl
src/Misc/Integer.jl
src/NumFieldOrd/NfOrd/Ideal/Ideal.jl
src/NumFieldOrd/NfOrd/Unit/UnitGrpCtx.jl
src/Sparse/Module.jl

This makes the types print nicer in e.g. a vector (similar to https://github.com/thofma/Hecke.jl/pull/1350)

Remove some trailing newlines from show methods

---

Project.toml

See https://github.com/thofma/Hecke.jl/commit/1398592225585c5666cb215f3cdb7f136e6a934e#commitcomment-137856547
@thofma can you just merge this without CI (and then tag again)?

chore: bump version to 0.25.0

---

src/AlgAssAbsOrd/PicardGroup.jl
src/ModAlgAss/Lattices/Morphisms.jl
src/NumFieldOrd/NfOrd/PicardGroup.jl
test/ModAlgAss/Lattices/Lattices.jl

The "ideal" type AlgAssAbsOrdIdl can be fractional.

fix: make `is_principal` working again

---

Project.toml
src/GrpAb/ChainComplex.jl
src/Hecke.jl
src/Misc/IJulia.jl
src/NumFieldOrd/NfOrd/NfOrd.jl
test/QuadForm/Torsion.jl

Refactors everything about name printing to only use the interface discussed in https://github.com/Nemocas/AbstractAlgebra.jl/pull/1594 (and no longer any internals)

Adapt to name printing changes in AA

---

src/NumField/QQ.jl
test/NumField/QQ.jl

This change makes the code in https://github.com/oscar-system/Oscar.jl/issues/2915#issuecomment-1801794028 run. And I find it nice to have for consistency (see https://github.com/oscar-system/Oscar.jl/issues/2915#issuecomment-1801794028).

Add `residue_ring(::ZZRing, ::ZZIdl)`

---

Project.toml
src/NumFieldOrd/NfOrd/Overorders.jl
test/NfOrd/Overorders.jl

- Basis matrices of orders must always be in Hermite normal form, either because of (improved) index calculations or for faster comparisons of orders.
- Some places violated the implicit HNF rule
- Add assertions to the code

fix: avoid duplicates in overorder computation

---

src/LocalField/Elem.jl
src/LocalField/Ring.jl
src/LocalField/pAdic.jl

- do not allow arbitrary nonsensical coercions
- provide absolute_coordinates(Qp, ...) with predetermined parent

feat: make valuation ring elements of local fields more robust

---

src/AlgAssAbsOrd/PIP/bley_johnston.jl
test/ModAlgAss/Lattices/Lattices.jl

Accept local_freeness argument in `_is_principal_with_data_bj`, similar to `_is_principal_with_data_etale`.
To avoid this error:
```julia
julia> fl = is_free(M)
ERROR: MethodError: no method matching _is_principal_with_data_bj(::Hecke.AlgAssAbsOrdIdl{…}, ::Hecke.AlgAssAbsOrd{…}; side::Symbol, local_freeness::Bool)
Closest candidates are:
_is_principal_with_data_bj(::Any, ::Any; side, _alpha) got unsupported keyword argument "local_freeness"
@ Hecke ~/.julia/packages/Hecke/AP42u/src/AlgAssAbsOrd/PIP/bley_johnston.jl:161
Stacktrace:
[1] kwerr(::@NamedTuple{…}, ::Function, ::Hecke.AlgAssAbsOrdIdl{…}, ::Hecke.AlgAssAbsOrd{…})
@ Base ./error.jl:165
[2] _is_principal(::Type, ::Hecke.AlgAssAbsOrdIdl{…}, ::Vararg{…}; kw::@Kwargs{…})
@ Hecke ~/.julia/packages/Hecke/AP42u/src/AlgAssAbsOrd/PIP.jl:41 …
```

isfree: fix another book-example

---

Project.toml
src/NumField/NfAbs/NfAbs.jl

See https://github.com/Nemocas/AbstractAlgebra.jl/pull/1664.
Once https://github.com/Nemocas/AbstractAlgebra.jl/pull/1664 is released, ~~the AA compat needs to be adapted and~~ this merged.

Adapt to deprecations introduced in AA

---

examples/MultDep.jl
src/AlgAss/AbsAlgAss.jl
src/AlgAss/AlgAss.jl
src/AlgAss/AlgGrp.jl
src/AlgAss/AlgMat.jl
src/AlgAssAbsOrd/LocallyFreeClassGroup.jl
src/AlgAssAbsOrd/Order.jl
src/AlgAssAbsOrd/ResidueRingMultGrp.jl
src/AlgAssRelOrd/Order.jl
src/Deprecations.jl
src/FieldFactory/ab_exts.jl
src/ModAlgAss/Lattices/Morphisms.jl
src/NumField/NfAbs/NfAbs.jl
src/NumFieldOrd/NfOrd/Clgp/Map.jl
src/NumFieldOrd/NfOrd/LinearAlgebra.jl
src/NumFieldOrd/NfOrd/MaxOrd/DedekindCriterion.jl
src/NumFieldOrd/NfOrd/NfOrd.jl
src/NumFieldOrd/NfOrd/ResidueField.jl
src/NumFieldOrd/NfOrd/Unit/Map.jl
src/NumFieldOrd/NfOrd/Unit/UnitGrpCtx.jl
src/NumFieldOrd/NfRelOrd/FracIdeal.jl
src/NumFieldOrd/NfRelOrd/NfRelOrd.jl
src/QuadForm/Lattices.jl
src/Sparse/HNF.jl
src/Sparse/Module.jl
test/AlgAss/AbsAlgAss.jl
test/AlgAss/AlgGrp.jl
test/NfAbs/NfAbs.jl
test/Sparse/HNF.jl

This is similar to https://github.com/Nemocas/AbstractAlgebra.jl/pull/1664.
`Val{T}` is a type and `Val(T)` its singleton object. This is the way it is described in the julia docs (https://docs.julialang.org/en/v1/manual/types/#%22Value-types%22).
I went through all the uses and corrected them.
For all exported functions where the parameter occurred in a docstring, I already added deprecations. If you want more deprecations, please let me know.

Fix uses of `Val` inside Hecke

---

src/Aliases.jl

This contains the breaking part of https://github.com/thofma/Hecke.jl/pull/1458.

Adapt `Aliases.jl` for breaking release

---

src/Deprecations.jl

They were removed from #1455 to make it non-breaking.
This PR should be marked as breaking and only merged in the preparation of the 0.31.0 release.

Re-add deprecations of #1455

---

src/Sparse/Row.jl
test/Sparse/Row.jl

Scaling with zero divisors led to zeros saved in the value-array.

scale_row! fixed

---

src/FieldFactory/ab_exts.jl
src/FieldFactory/conductors_generic.jl
test/RCF/rcf.jl

- allow to provide conductors
- fix handling of implicit maximal order

feat: extend abelian_extension for number fields

---

src/LocalField/Elem.jl
test/LocalField/LocalField.jl

- `canonical_unit` was missing, which made the printing
of rational functions fail

fix: missing ring interface function for local fields

---

Project.toml
src/Deprecations.jl
src/GrpAb/GrpAbFinGen.jl
src/exports.jl
test/GrpAb/GrpAbFinGen.jl

cf. https://github.com/oscar-system/Oscar.jl/pull/3667#issuecomment-2091079080
Alternative to and thus closes #1483.

Try to sort out the homs

---

src/NumField/NfAbs/Simplify.jl
test/NfAbs/Simplify.jl

- simplify(...; canonical = true) relies on
simplify(...; canonical =  false) returning a nice defining
polynomial (nice = monic and integral coefficients)
- Closes #1490

fix: simplify for non-monic input

---

src/Sparse/Row.jl
src/Sparse/ZZRow.jl

This is obviously pointless and incurs allocations. At the same time it
is a relatively common case in Oscar, so optimizing this pays off.

sparse_row: don't sort 1-element lists

---

src/NumFieldOrd/NfOrd/TorsionUnits.jl
test/NfOrd/TorsionUnits.jl

I verified it works again via this:
```
julia> K, a = cyclotomic_field(13, cached = false);
julia> O = maximal_order(K);
julia> G, mG = torsion_unit_group(O)
(Z/26, Map: G -> O)
julia> length(Hecke._torsion_units_lattice_enum(O)[1])
26
```
Either something like that should be turned into a test -- or alternatively this undocumented function could be deleted, as nothing calls it.

Repair _torsion_units_lattice_enum

---

src/AlgAss/AlgMat.jl
src/AlgAss/AlgMatElem.jl
src/AlgAss/Types.jl

The second type param is fully determined by the first and third,
so get rid of it.

Simplify MatAlgebraElem type params

---

src/LocalField/Completions.jl
test/LocalField/Completions.jl

My educated guess is that `setprecision!(::CompletionMap, ...)` should change the precision of the codomain (if any).
Related to #1509.

Maybe fix 1509

---

src/QuadForm/Misc.jl
test/QuadForm/Herm/GenusRep.jl

- if P^n is principal, so is P^(n mod ord(P)), so we can always
assume that exponents are nonnegative by reducing modulo the
order
- closes #1152

bug: fix _find_quaternion_algebra

---

Project.toml
src/GrpAb/Map.jl

- Use to a SolveContext to cache the implicit normal form
computations

feat: make has_preimage_with_preimage faster for abelian groups

---

src/LocalField/ResidueRing.jl
src/LocalField/Ring.jl
src/NumFieldOrd/NfOrd/StrongEchelonForm.jl
test/LocalField/ResidueRing.jl

Use the Howell form for linear solving over the new `LocalFieldValuationRingResidueRing`s.
The `kernel` method is copied from the `zzModMatrix` version in Nemo. I have no idea whether this is correct; it seems to work.

Linear solving for p-adic residue rings

---

src/GrpAb/ChainComplex.jl
test/GrpAb/GrpAbFinGen.jl

The first commit is part of https://github.com/oscar-system/Oscar.jl/pull/3815.
The second commit makes `free_resolution(::FinGenAbGrp)` work again, and also the printing of its return value. This seems to be some fallout from the `rank` -> `torsion_free_rank` thing. And I added a dummy test to keep this working in the future (but without real test).

Add missing parentheses in complex printing and fix `free_resolution(::FinGenAbGrp)`

---

src/NumFieldOrd/NfOrd/Ideal/Ideal.jl
test/NumFieldOrd/NumFieldOrd.jl

ideal comparison had an algorithmic error, leading to rare crashes in the CI (for Oscar)

fixes Oscar#3841

---

src/LocalField/Elem.jl
src/LocalField/LocalField.jl
src/LocalField/Ring.jl
src/LocalField/Types.jl
test/LocalField.jl
test/LocalField/Ring.jl

Mostly moves around code in `src/LocalField/Ring.jl` and adds conformance tests.
Also adds a bit nicer printing, makes `valuation_ring` an attribute of the field and fixes `canonical_unit`.

Clean up `LocalFieldValuationRing` a bit

---

src/NumFieldOrd/NfOrd/FracIdeal.jl

feat: copy less things

---

src/LinearAlgebra/FakeFmpqMat.jl

Nothing uses them and the names are suboptimal (so if someone
needs this functionality we'd be better of implementing these
as `convert` methods or constructors or something like that).

Remove unused to_array and to_fmpz_mat methods

---

src/LocalField/Completions.jl
src/LocalField/Elem.jl
src/LocalField/LocalField.jl
src/LocalField/Types.jl

This should make some things a bit faster in the local fields.
I had timings where `_p_adic_regulator` was twice as fast as before, but the timings differ largely accross julia sessions.
This closes #1537 as far as I am concerned.
Not all changes here are "trivial", so someone should have a look (once the CI is green).

Optimize local fields a bit

---

src/Misc/PIDIdeal.jl

Hopefully resolves the failing checks in https://github.com/Nemocas/AbstractAlgebra.jl/pull/1731

Compatibility with AbstractAlgebra ideal interface

---

src/AlgAss/AlgQuat.jl
src/AlgAss/Map.jl
src/AlgAssRelOrd/Ideal.jl
src/AlgAssRelOrd/Order.jl
src/EllCrv/Heights.jl
src/Sparse/Row.jl
test/AlgAss/AlgQuat.jl

- add `check` for constructors of morphisms
- fix principal ideal test code in quaternion algebras
- fix equality of (relative) orders

feat: improve algebra functionality

---

src/AlgAss/AlgAss.jl
src/AlgAssAbsOrd/LocallyFreeClassGroup.jl
src/GenOrd/Ideal.jl
src/Misc/Poly.jl

The function _zero_algebra was renamed to zero_algebra some time ago, but not all places calling it were updated.
I found this because it caused a bunch of invalidations in code found while investigating #746 (indirectly, of course, as any actual call to `_zero_algebra` could not have worked).

Change _zero_algebra -> zero_algebra

---

src/Map/automorphisms.jl
test/Map/NumberField.jl

Before
```
julia> Qt, t = QQ["t"]
(Univariate polynomial ring in t over QQ, t)
julia> K, a = number_field(t+1)
(Number field of degree 1 over QQ, -1)
julia> automorphism_list(K)
ERROR: Data does not define a morphism
Stacktrace:
[1] error(s::String)
@ Base ./error.jl:35
[2] #map_data#323
@ ~/.julia/packages/Hecke/CoyAD/src/Map/NumField.jl:281 [inlined]
[3] map_data
@ ~/.julia/packages/Hecke/CoyAD/src/Map/NumField.jl:272 [inlined]
[4] #hom#322
@ ~/.julia/packages/Hecke/CoyAD/src/Map/NumField.jl:150 [inlined]
[5] hom
@ ~/.julia/packages/Hecke/CoyAD/src/Map/NumField.jl:137 [inlined]
[6] _automorphisms(K::AbsSimpleNumField; is_abelian::Bool)
@ Hecke ~/.julia/packages/Hecke/CoyAD/src/Map/automorphisms.jl:29
[7] automorphism_list(K::AbsSimpleNumField; copy::Bool, is_abelian::Bool)
@ Hecke …
```

Fix `_automorphisms` for degree 1 number field

---

src/GrpAb/Elem.jl
src/GrpAb/Map.jl

Note that some of the replaced code was potentially wrong: it passed `A.snf` instead of `A.hnf` to `reduce_mod_hnf_ur!`. But I did not bother to see if this actually leads to problems.

Introduce `assure_reduced!(A::FinGenAbGroup, a::ZZMatrix)`

---

Project.toml
src/exports.jl

To make progress with https://github.com/oscar-system/Oscar.jl/pull/4122.

Export `absolute_base_field`

---

src/LocalField/neq.jl

Given an element of norm 1, Hilbert 90 assures it can be written as sigma(x)/x
Generically, this is solves via Lagrage resolvent and randomization. (frobenius_equation). If this fails, a much slower method is called\that constructs the element digit-by-digit (frobenius_equation2). The 1st function has to increase (temporarily) the precision. However then the norm 1 condition is no longer true... and thus the input for the second function illegal hence the failure.

Fixes Serre (improves #1428)

---

src/GrpAb/Elem.jl
src/HeckeTypes.jl

This reduce allocations and increases speed of code using these elements.
Using the same example as in https://github.com/oscar-system/Oscar.jl/pull/4119, we get the following.
Before this PR here:
julia> @btime is_homogeneous(f);
1.533 μs (62 allocations: 2.28 KiB)
julia> @btime is_homogeneous(F);
3.932 μs (152 allocations: 5.53 KiB)
With just this PR:
julia> @btime is_homogeneous(f);
1.404 μs (48 allocations: 2.00 KiB)
julia> @btime is_homogeneous(F);
3.688 μs (116 allocations: 4.56 KiB)
With just https://github.com/oscar-system/Oscar.jl/pull/4119:
julia> @btime is_homogeneous(f);
334.071 ns (10 allocations: 416 bytes)
julia> @btime is_homogeneous(F);
556.150 ns (12 allocations: 656 bytes)
With this PR and https://github.com/oscar-system/Oscar.jl/pull/4119:
julia> @btime …

Turn `FinGenAbGroupElem` into a non-mutable struct

---

src/NumField/NfAbs/Conjugates.jl
test/NfAbs/Conjugates.jl

As discussed with @fieker, @lgoettgens and @joschmitt on Friday at the OSCAR workshop I've added a `Base.conj` method for `AbsSimpleNumFieldElem`. The main purpose of this is to provide an easy way to conjugate cyclotomic numbers interactively (for actual implementations `complex_conjugation` should be better). After looking at the code I'm not sure why checking the parent field should be necessary. I think we can leave all the checks to `complex_conjugation`.

Add `Base.conj` for `AbsSimpleNumFieldElem`

---

Project.toml
ext/GAPExt/abelian_layer.jl
ext/GAPExt/brauer.jl
ext/GAPExt/conductors.jl
ext/GAPExt/fields.jl
ext/GAPExt/maximal_abelian_subextension.jl
ext/GAPExt/meataxe.jl
src/FieldFactory/CM_recognition.jl

If Oscar.jl wants to use GAP.jl 0.12.0 then the Hecke.jl dependencies must allow GAP.jl 0.12 (see oscar-system/Oscar.jl/pull/4086).

bump version number, in order to allow for GAP.jl 0.12

---

src/RCF/conductor.jl

fixes Simon's problem on slack:
julia> F, a = cyclotomic_field(7,:a)
(Cyclotomic field of order 7, a)
julia> P,x = polynomial_ring(F,:x)
(Univariate polynomial ring in x over F, x)
julia> FG,dd = number_field(x^6 + (133486969//288*a^5 - 223759151//432*a^4 - 223759151//432*a^3 + 133486969//288*a^2 - 232474865//288)*x^3 - 840539241479//13824*a^5 - 18036715089631//9216*a^4 - 18036715089631//9216*a^3 - 840539241479//13824*a^2 - 7320065966297//9216) (Relative number field of degree 6 over F, _$)
julia> is_abelian(FG)
ERROR: Number field element not in the order
Stacktrace:
...
The same problem (plus some more) also would have prevented maximal_abelian_subfield(FG, of_closure = true)
to have been correct
The runtime of those examples is a bit high for testing (always)

fix is_abelian (and some more)

---

src/Sparse/Rref.jl

Without this change, the compiler only infers `Union{dense_matrix_type(C), Nothing}`, as it does not know that the if/elseif clause get always taken due to the check in the beginning. Adding this explicit error  removes `Nothing` from the possible return types.

Make `kernel(::SMat)` better infereable

---

src/EllCrv/NewtonLift.jl

Reduces the default value since otherwise computations take too long. 
An early abort will have to wait until #1509 and the likes are resolved.

Reduce default for max_precision in newton_iteration

---

src/Misc/Cartesian.jl
src/Misc/Integer.jl
src/Misc/Poly.jl
src/Misc/Primes.jl
src/Sparse/Matrix.jl
src/Sparse/Row.jl

The docstring of `eltype` states
> However the form that accepts a type argument should be defined for new types. 
Chaning this should help julia infer types of iterator constructions like `Iterators.reverse(...)` for these types.
Furthermore, there were some methods installed that never triggered, e.g. `eltype(::Type{SMat{T}}) where T` does not get used as `SMat` has two type params. Changing this to  `eltype(::Type{<:SMat{T}}) where T` fixes this

Change `eltype` methods for objects to types

---

docs/src/.vitepress/config.mts
docs/src/manual/developer/documentation.md
src/Hecke.jl

doc: add instructions to build documentation

---

examples/Det.jl
src/AlgAss/Elem.jl
src/AlgAss/Map.jl
src/AlgAssAbsOrd/PIP/bley_johnston.jl
src/Hecke.jl
src/LinearAlgebra/LatEnum.jl
src/Misc/CRT.jl
src/Misc/Matrix.jl
src/NumFieldOrd/NfOrd/Ideal/Arithmetic.jl
src/NumFieldOrd/NfOrd/ResidueRing.jl
src/QuadForm/Enumeration.jl

Also switch to Nemo.denominator! and Nemo.numerator!,
and remove add_two! which now is equivalent to `add!(x, 2)`.

Use set!, zero!, etc. in YET more places

---

src/NumFieldOrd/NfOrd/LinearAlgebra.jl
test/LinearAlgebra/SolveIntegral.jl

- Take into account, that the pseudo-HNF might have zero rows

fix: linear solving over rings of integers

---

docs/src/manual/abelian/elements.md
src/GrpAb/Elem.jl
src/exports.jl
test/GrpAb/Elem.jl

@simonbrandhorst suggested that instead of accessing the property using the dot notation, a proper getter would be useful. I named the method `components` since this is how it is referred to in the docs.

Add `components` method to Abelian group

---

src/NumField/NfAbs/NfAbs.jl
src/NumField/SimpleNumField/Subfields.jl
src/exports.jl

fix: export `is_subfield_normal` and `principal_subfields`

---

src/Sparse/Row.jl
test/Sparse/Row.jl

Some issues in `add_scaled_row!` were fixed in #1591, but not to
`add_right_scaled_row!`. Rectify this by merging the two functions
into one.

Fix bug in `add_right_scaled_row!`

---

src/NumFieldOrd/NfOrd/Clgp/Saturate.jl
src/NumFieldOrd/NfOrd/ResidueRingMultGrp.jl
test/NfOrd/Clgp.jl

Use baby-step-giant-step algorithm for large primes to make
the complexity not linear in the order.
Before (saturating at ~2^25):
```julia
96.520001 seconds (56.86 k allocations: 120.018 GiB, 17.87% gc time)
```
With this PR:
```julia
2.726522 seconds (70.38 M allocations: 1.101 GiB, 30.02% gc time)
```

fix: saturation at large primes

---

docs/src/.vitepress/config.mts
docs/src/manual/algebras/groupalgebras.md
src/AlgAss/AbsAlgAss.jl
src/AlgAss/AlgGrp.jl
src/AlgAss/Elem.jl
src/AlgAss/Types.jl
src/Grp/GenGrp.jl
src/GrpAb/GrpAbFinGen.jl
test/AlgAss/AlgGrp.jl
test/AlgAss/Elem.jl

Due to popular demand, group algebras with sparse representation (aka "don't crash with large groups"). Needs some work/clean up:
```
julia> G = SymmetricGroup(10)
Full symmetric group over 10 elements
julia> QG = group_algebra(QQ, G)
Group algebra
of full symmetric group over 10 elements
over rational field
julia> a = QG(rand(G)); b = QG(rand(G));
julia> c = (a + b) * (a - b)
(1,2,4,8,7)(3,9,10,5,6) - (1,4,9)(2,10,3,6,7,5,8) + (1,7,3,8,6,10,4)(2,9,5) - (1,2,6)(3,9)(4,5)
```
@royess this might interest you. It is similar to your approach.
Small todo:

feat: group algebras with sparse representation

---

examples/IsPower.jl
src/Misc/Matrix.jl
src/QuadForm/LineOrbits.jl

This old syntax has been deprecated for a long time

Fix @GC.preserve -> GC.@preserve

---

src/Hecke.jl

Remove strange checkbounds method

---

Project.toml
src/Sparse/Row.jl
src/Sparse/ZZRow.jl
test/Sparse/Row.jl

Add mutating arithmetics for SRow with the interface from AA. Inspired by https://github.com/oscar-system/Oscar.jl/pull/4228#discussion_r1812044722 by @fingolfin .
Furthermore, make some of the existing functions easier to use by letting them coerce scalars (if needed) and add automatic workarounds for assertions.
I tested the new methods locally using `test_mutating_op_like_*` from AA. Unfortunately, for CI this does not work atm as there is too much expected missing for SRows (like random elements, `zero`, ...).
This currently contains https://github.com/thofma/Hecke.jl/pull/1658 to avoid conflicts.
@fingolfin could you have a look at the methods added here as well?

Add mutating arithmetic for `SRow`s

---

src/AlgAss/AlgGrp.jl
src/AlgAss/Elem.jl
src/AlgAss/Types.jl
test/AlgAss/AlgGrp.jl

These were the necessary changes to make (sparse) group algebras with an (infinite) additive group that is not `FinGenAbGroup`.
To find these things, I defined a thin wrapper around `FinGenAbGroup` and tried to make that work with the existing things.
```julia
struct FooGroup <: AbstractAlgebra.AdditiveGroup
G::FinGenAbGroup
end
struct FooGroupElem <: AbstractAlgebra.AdditiveGroupElem
x::FinGenAbGroupElem
end
elem_type(::Type{FooGroup}) = FooGroupElem
parent_type(::Type{FooGroupElem}) = FooGroup
parent(x::FooGroupElem) = FooGroup(parent(x.x))
is_abelian(G::FooGroup) = is_abelian(G.G)
is_finite(G::FooGroup) = is_finite(G.G)
order(T, G::FooGroup) = order(T, G.G)
order(G::FooGroup) = order(G.G)
length(G::FooGroup) = length(G.G)
function Base.iterate(G::FooGroup)
it = iterate(G.G) …
```

fix: group algebras of additive groups with sparse rep

---

src/Map/NumberField.jl

The `is_surjective` function for `NumFiledHom` has a misplaced bracket.

fix misplaced bracket for maps

---

src/NumFieldOrd/NfOrd/LinearAlgebra.jl
test/NfOrd/LinearAlgebra.jl

It seems natural to have an 'is_empty'-method for pseudo-matrices, so this commit adds one. I also added a couple of tests.

is_empty for pseudo-matrices

---

src/EllCrv/EllCrv.jl
src/EllCrv/Isomorphisms.jl
src/EllCrv/LocalData.jl
src/FunField/Differential.jl
src/FunField/Divisor.jl
src/GrpAb/Dual.jl
src/NumField/ComplexEmbeddings/NfAbs.jl
src/NumField/ComplexEmbeddings/NfRel.jl
src/NumField/QQ.jl
src/NumFieldOrd/NfOrd/MaxOrd/Polygons.jl
src/NumFieldOrd/NfOrd/NfOrd.jl
src/QuadForm/QuadBin.jl

A lot of progress towards https://github.com/oscar-system/Oscar.jl/issues/2222 and https://github.com/thofma/Hecke.jl/issues/1594.
I tried to use as much information from the corresponding `==` method to make the hash as good as possible.
Once this is merged and released, could you @thofma update the list in https://github.com/thofma/Hecke.jl/issues/1594 (I'll do the same for https://github.com/oscar-system/Oscar.jl/issues/2222), so that we can see what's left to work on?

Add many hash functions

---

src/Hecke.jl

We have AbstractAlgebra.factor === Hecke.factor these days
Resolves https://github.com/oscar-system/Oscar.jl/issues/4034

Remove circular delegating factor -> factor

---

src/Misc/Poly.jl
src/NumFieldOrd/NfOrd/Ideal/Valuation.jl
test/Misc/Poly.jl
test/NfOrd/Ideal/Prime.jl

- also fix Hensel lifting in the trivial case

fix: valuation for inert primes

---

src/Hecke.jl
src/LocalField/LocalField.jl
src/Map/NumField.jl
src/Misc/RelFiniteField.jl

Also remove redundant dense_poly_type methods.

Uniform base_field_type handling

---

src/AlgAss/Elem.jl
test/AlgAss/Elem.jl

Given an instance `A` of a subtype of `Hecke.AbstractAssociativeAlgebra{T}`, trying
```julia
divexact(zero(A), zero(A))
```
would result in a `BoundsError` instead of the usual `ErrorException`, due to `r == 0` in the Elem.jl.
This commit fixes this an also adds two small tests.

Small fix of is_divisible (and divexact) + tests

---

src/AlgAss/AlgGrp.jl

It seems there is a minor space typo as there is no space after order 5 in the output below:
```
julia> C = abelian_group(5);
julia> GA = group_algebra(GF(3), C);
julia> d = decompose(GA);
julia> d[1][2]
Map
from structure constant algebra of dimension 1 over GF(3)
to group algebra of group of order 5over GF(3)
```
I think the first output line is printed correctly from: https://github.com/thofma/Hecke.jl/blob/3f9f55b0c1e1c2c013f3ecd60d0000aba86d121a/src/AlgAss/StructureConstantAlgebra.jl#L362-L363
It seems the typo is due to this line, no space before over, it should be `" over " `as in the earlier clause
https://github.com/thofma/Hecke.jl/blob/3f9f55b0c1e1c2c013f3ecd60d0000aba86d121a/src/AlgAss/AlgGrp.jl#L185
Please help review this PR, thank you!

fix: minor space typo in the `AbsAlgAssMor` output after decomposition of `group_algebra`

---

Project.toml

Draft as GAP.jl 0.13.0 is not released yet.

Allow GAP.jl 0.13

---

src/LocalField/LocalField.jl
src/Misc/RelFiniteField.jl
src/NumField/Embedded.jl

This contains the fixes from #1707 but could be merged right away.

Some fixes

---

README.md
src/AlgAss/AlgGrp.jl
src/GenOrd/GenOrd.jl
src/NumFieldOrd/NfOrd/NfOrd.jl
src/NumFieldOrd/NfOrd/ResidueRing.jl

Also tweak how the bases are printed (print basis vector as `[x, y]` instead of `T[x,y]`)

Use `Lowercase` in some `show` methods

---

src/HeckeTypes.jl
src/LinearAlgebra/FakeFmpqMat.jl

They are already stored in the wrapped ZZMatrix

FakeFmpqMat: don't store rows & cols

---

docs/make.jl

If https://github.com/thofma/Hecke.jl/pull/1735 is merged, this needs to be merged as well. Otherwise, the "Build docs" CI job will fail for dependabot PRs. See https://github.com/oscar-system/Oscar.jl/pull/4554 for more details.

Skip doc preview for dependabot PRs

---

src/Misc/UnsafeRational.jl

to silence the warnings introduced in https://github.com/JuliaLang/julia/pull/57311.

Explicitly qualify constructors that are extended

---

src/AlgAss/StructureConstantAlgebra.jl
src/AlgAssAbsOrd/Ideal.jl
src/AlgAssAbsOrd/Order.jl
src/AlgAssAbsOrd/Types.jl
src/ModAlgAss/Lattices/Basics.jl

@fieker now it is the same as for `GenOrd`. First the field/algebra, then the "base ring".

feat: swap type parameter order for orders in algebras

---

src/GenOrd/GenOrd.jl
src/LocalField/PowerSeries.jl
src/LocalField/ResidueRing.jl
src/LocalField/Ring.jl
src/NumField/Embedded.jl
src/Sparse/Row.jl
test/GenOrd/GenOrd.jl
test/LocalField/PowerSeries.jl
test/LocalField/ResidueRing.jl
test/LocalField/Ring.jl
test/NumField/Embedded.jl
test/Sparse/Row.jl
test/setup.jl

Make use of the new submodule structure and names introduced in https://github.com/Nemocas/AbstractAlgebra.jl/pull/1954.
For some types I encountered multiple `test_elem` methods in different files. I did my best trying to somehow merge them together, but it would be good if someone with domain knowledge had a second look if they still do mathematically sensible things. See be21c136bd4c9c0714d144444a6861796a37b3d8 for the relevant changes.

Adapt to conformance test changes in AA

---

docs/src/manual/quad_forms/integer_lattices.md
src/QuadForm/ShortVectors.jl

In order to avoid breaking OSCAR, we had to add an extra function in Hecke, related to `short_vectors_affine` (https://github.com/thofma/Hecke.jl/pull/1729). Now that we have removed redundant code in https://github.com/oscar-system/Oscar.jl/pull/4583, we can remove this function.
I also fixed some documentation, to have properly one doc-string for each of the two `short_vectors_affine` functions since they behave slightly differently (coordinates of vectors).
As I mentioned in https://github.com/oscar-system/Oscar.jl/pull/4583#discussion_r1963374282, I needed to adapt the code of `enumerate_quadratic_triples` because `_convert_type` might not work for `ZZMatrix` in entry. The simple fix is to force conversion of the inputs into `QQMatrix` if they are not already.

Followup after changes in OSCAR

---

src/AlgAssAbsOrd/ICM.jl
test/AlgAssAbsOrd/ICM.jl

Assert condition can only hold if ideals are isomorphic

fix: mend assert order

---

src/FunField/Divisor.jl
src/GenOrd/FractionalIdeal.jl
src/exports.jl
test/FunField/Divisor.jl
test/GenOrd/Ideal.jl

- `gcd` for divisors
- `trivial_divisor`
- fix bug with `0 * D`
@BD-00 this makes your example work with
```
function _compose(a::node{Divisor}, b::node{Divisor}, check = false)
if check && !iszero(gcd(a.content, b.content))
error("input not coprime")
end
return node{Divisor}(a.content + b.content, a, b)
end
```

feat: add more operations for divisors

---

Project.toml
src/LocalField/Elem.jl

AA 0.44.13 provides a generic default method, which also
handles zero correctly.

Remove canonical_unit(x::LocalFieldElem)

---

src/Sparse/Row.jl
src/Sparse/ZZRow.jl
test/Sparse/Row.jl

Positions need to be unique
(I tried to make it as cheap as possible, but we could also add a `check` to eliminate the check completely.)

fix: add verification in sparse row constructor

---

.github/workflows/CILong.yml
.github/workflows/oscar.yml

Same as https://github.com/Nemocas/Nemo.jl/pull/2088.
This should fix the downstream tests. As this may happen with all of Polymake.jl (at least in theory), it is safest to do just in all CI jobs that may run Polymake.jl.

Add workaround for GLIBCXX issue with julia 1.6

---

src/QuadForm/Herm/GenusRep.jl
src/QuadForm/Herm/Mass.jl
src/QuadForm/Quad/GenusRep.jl
src/QuadForm/Quad/ZGenusRep.jl

This should help us to use randomness, like in the case of `ZZLat`, for enumerating genera of hermitian lattices which start to have "large" rank.
I have re-used the structure introduced in the file `QuadForm/Quad/ZGenusRep.jl`: the goal would be to merge both into a unique structure which could be used in the future for `QuadLat` also, for instance... I still have to think about how to homogenize everything. Probably using some `Ctx` type.
I introduce the possibility to enumerate random lines, and add some invariants for, hopefully, speed up lattice comparison.
I have been able to enumerate one of the hard case given in https://github.com/thofma/Hecke.jl/issues/557 in under 40 minutes (while it took around a day before), and I am trying the second one currently, which did not finish …

feat: enumeration of large definite hermitian genus

---

src/QuadForm/Quad/ZLattices.jl
test/QuadForm/Quad/ZLattices.jl

The extended $A_1$-lattice needs a particular treatment and this was not done previously because of the condition in line 3271. And as far as I know, the extended $D_n$-lattices are defined only for $n \geq 4$.

fix: `extended_ade`

---

src/QuadForm/Herm/GenusRep.jl

I have written a `getindex` function locally for `LineEnumCtx` but I am not sure we want it, so instead I keep track of whether or not we have used the automorphisms (sometimes all isometries are given by scalar multiplication so we have to fallback to a regular `enumerate_lines`... We should not `collect` it since it could consist of many lines).

fix: avoid calling a nondefined `getindex` function

---

src/NumField/Elem.jl
src/NumField/NfAbs/NonSimple.jl
test/NfAbs/Elem.jl
test/NfAbs/NonSimple.jl

Apparently `is_rational` was defined already but not callable from outside the module. 
fixes #1909

Add `isinteger` and `is_rational` for `AbsNonSimpleNumFieldElem`

---

src/Hecke.jl

This now uses exactly the same logic as https://github.com/Nemocas/Nemo.jl/pull/2127.

Use `Base.pkgversion` to query the Hecke version

---

.github/workflows/CILong.yml

Jobs complain that the requested arch does not work and taking the default would be better, see e.g. https://github.com/thofma/Hecke.jl/actions/runs/17233301753/job/48892203435?pr=1961#step:3:8

CI: don't specify architecture

---

docs/src/manual/algebras/quaternion.md
src/AlgAss/AlgQuat.jl
src/Aliases.jl

I stumbled over the fact that for number fields conjugation is called `conj` (as in `Base`), but for quaternions it is `conjugate`.
I hope the alias does not cause some horrible fall-out.

Make `conj` and `conjugate` synonymous

---

src/QuadForm/Quad/ZLattices.jl
src/exports.jl
test/QuadForm/Quad/ZLattices.jl

Contained in https://github.com/oscar-system/Oscar.jl/pull/5151, but it does not require to use OSCAR so I moved it here.

feat: enumeration of even root lattices/symbols

---

src/Misc/Integer.jl
test/Misc/Integer.jl

(Currently `modord(a, 1)` runs into an infinite loop.)
The definition makes sense if one interprets the mult. order of a mod m as the smallest positive integer d such that m divides a^d-1.

define `modord(a, 1) = 1`

---

src/Sparse/Row.jl

Before:
```julia-repl
julia> R=ZZ; v=R(1);
julia> @btime sparse_row($R, [(1,$v)])
124.772 ns (9 allocations: 416 bytes)
Sparse row with positions [1] and values ZZRingElem[1]
julia> @btime sparse_row($R, [1],[$v])
107.479 ns (11 allocations: 464 bytes)
Sparse row with positions [1] and values ZZRingElem[1]
julia> @btime sparse_row($R, 1, $v)
178.194 ns (14 allocations: 528 bytes)
Sparse row with positions [1] and values ZZRingElem[1]
julia> @btime sparse_row($R, 1, $v; check=false)
175.253 ns (14 allocations: 528 bytes)
Sparse row with positions [1] and values ZZRingElem[1]
```
After:
```julia-repl
julia> @btime sparse_row($R, 1, $v)
96.549 ns (7 allocations: 208 bytes)
Sparse row with positions [1] and values ZZRingElem[1]
julia> @btime sparse_row($R, 1, $v; check=false)
96.796 ns (7 …
```

Fix performance of `sparse_row(::ZZRing,::Int,::ZZRingElem)`

---

src/NumField/NfAbs/Elem.jl

Soon Nemo will be updated so that "coercion" of polynomials has to be effected via `map_coefficients`; this update is intended to avoid consequent problems in Hecke.

Use map_coefficients instead of soon-to-be-forbidden coercion
