thofma/Hecke.jl

test/Misc/Powmod_test.jl, test/Misc/Powres_test.jl
=> Tests for powmod and power residue symbol

src/Misc.jl, src/Misc/MPolyFactor.jl, test/Misc.jl, test/Misc/MPolyFactor.jl
now you can do
```
julia> R, (x, y, z) = PolynomialRing(Hecke.QQ, ["x", "y", "z"])
(Multivariate Polynomial Ring in x, y, z over Rational Field, fmpq_mpoly[x, y, z])
julia> factor_squarefree((x+y^2)*(x^2-y^2)^7)
1 * (x + y^2) * (x^2 - y^2)^7
julia> factor((x+y^2)*(x^2-y^2)^7)
1 * (x + y^2) * (x - y)^7 * (x + y)^7
=> start MPolyFactor.jl

src/AlgAssAbsOrd/Similarity.jl
Problem: R = Z/large number
divrem(large, 1) took forever
not sure that the approach via coprime_base is optimal, but it should be
correct (and yield optimal division chains)
=> fix divrem for nmod and provide for fmpz_mod

src/HeckeTypes.jl, src/NfOrd/Clgp/FacBase_Idl.jl
as a bid to do large roots in PIP
=> parametrize FactorBaseSingleP to support fmpz

test/NumField/NfAbs.jl, test/NumField/NfAbs/MPolyGcd.jl
=> Add MPolyGcd example of Dan

test/QuadForm/Quad/ZLattices.jl
=> Added test for norm in ZLattices

src/QuadForm/Torsion.jl
submodules for TorQuadMod and rels
=> submodules for torsion quadratic modules

src/Misc/Integer.jl, src/NumField/NfAbs/Elem.jl, src/QuadForm/Quad/Spaces.jl
=> issquare_with_root -> issquare_with_square_root

src/QuadForm/PadicLift.jl, src/QuadForm/Quad/NormalForm.jl, test/QuadForm/PadicLift.jl
=> Clean up for PadicLift.jl

src/NumField/NfRel/FracIdeal.jl, src/NumField/NfRel/Ideal.jl, src/NumField/NfRel/NfRelOrd.jl, src/NumField/NfRel/Types.jl, test/NfRel/FracIdeal.jl, test/NfRel/Ideal.jl
@joschmitt In case you want to see my fix.
=> Fix modular computations for ideal arithmetic (relative)

src/QuadForm/MassQuad.jl, test/QuadForm/MassQuad.jl
Added tests for negative values as well.
=> fix kronecker

src/QuadForm/Quad/ZGenus.jl
=> avoid stack overflow

src/QuadForm/Torsion.jl, test/QuadForm/Quad/ZGenus.jl
and a bug in normal_form for TorQuadMod
=> fix a bug in sub which resulted in different moduli 

examples/PolyRoot.jl, examples/Suri.jl, src/EllCrv/EllCrv.jl, src/EllCrv/Finite.jl, src/Hecke.jl, src/Map/automorphisms.jl, src/Misc/Integer.jl, src/Misc/Poly.jl, src/Misc/UnitsModM.jl, src/Misc/nmod_poly.jl, src/Misc/power_residue_symbol.jl, src/ModAlgAss/MeatAxe.jl, src/NfOrd/Clgp/Saturate.jl, src/NfOrd/Elem.jl, src/NfOrd/Hensel.jl, src/NfOrd/Ideal/Prime.jl, src/NfOrd/RayClassGrp.jl, src/NfOrd/ResidueRing.jl, src/NfOrd/ResidueRingMultGrp.jl, src/NfOrd/TorsionUnits.jl, src/NumField/NfAbs/NfAbs.jl, src/NumField/NfRel/NfRel.jl, src/NumField/NfRel/NfRelNSMor.jl, test/Misc/Powmod_test.jl
Merge the following first:
https://github.com/Nemocas/AbstractAlgebra.jl/pull/758
https://github.com/Nemocas/Nemo.jl/pull/995
=> powmod -> powermod. Addresses Nemo # 988

src/LocalField/Poly.jl, src/NumField/SimpleNumField/Subfields.jl, test/LocalField.jl, test/LocalField/Poly.jl
=> resultant for padic polynomials fixed

src/Misc/Integer.jl
Fixes https://github.com/thofma/Hecke.jl/issues/259
=> fix factor using coprime_base, fixes @259

src/GrpAb/GrpAbFinGen.jl, src/GrpAb/Map.jl
- internally, create homs with check = false
- add haspreimage(map, vector)
- add special case in preimage for known prime exponent
- set exponent on direct products
=> various minor things to hom of GrpAb:

src/Misc/Poly.jl
This is the Hecke counterpart to https://github.com/Nemocas/AbstractAlgebra.jl/pull/840
I have no way to test this PR at the moment, but it is expected to fail until that AA PR and other PR's against Hecke are merged.
=> Move polynomial function to AbstractAlgebra's Misc directory.

src/QuadForm/Herm/Genus.jl
=> disc -> discriminant

src/FieldFactory/fields.jl, src/NumField/NfAbs/Simplify.jl
=> keyword argument fixes in simplify

src/QuadForm/Quad/NormalForm.jl
As suggested by @8d1h (thanks)
(Note: both spellings are allowed, but we should settle on one. Right now, the majority uses "homogeneous", hence I picked that. But we could also go the other way).
=> homogenous -> homogeneous

Project.toml, src/Misc/CRT.jl, src/Misc/FiniteField.jl, src/Misc/Poly.jl, src/NfOrd/Hensel.jl, src/NumField/SimpleNumField/Field.jl
Closes #269 
Closes #284 
Closes #271 
Closes #286
=> Bump dependencies

Project.toml
=> Bump Nemo & AA version

docs/make.jl, docs/mkdocs.yml, docs/src/function_fields/basics.md, docs/src/function_fields/degree_localization.md, docs/src/function_fields/elements.md, docs/src/function_fields/internal.md, docs/src/function_fields/intro.md, src/FunField/DegreeLocalization.jl
Unfortunately I can't test locally. It seems like there is some kind of unsatisfiable dependency.
Anyway, I was able to tell what conventions you have in docs, so I'll leave it to you to rearrange as you prefer.
=> Add function field documentation to new directory.

src/Misc/CRT.jl, src/Misc/FiniteField.jl
- fast, but dodgy Frobnenius
- better iterating
- fewer overhead
=> improve modular_proj for FacElem{fq_nmod}, essentially

src/LocalField/Elem.jl, src/LocalField/LocalField.jl, src/LocalField/Poly.jl, src/LocalField/qAdic.jl, src/NfOrd/MaxOrd/Polygons.jl, test/LocalField/LocalField.jl
=> norm fixed

src/Misc/Matrix.jl
Fixes #377.
Silly me, of course it works! I just copied the code from `nullspace` in AbstractAlgebra, since it does the identical thing.
I ran the tests from @wbhart's AA PR repeatedly and they passed.
=> Fix can_solve_with_kernel

src/GrpAb/GrpAbFinGen.jl, test/GrpAb/GrpAbFinGen.jl
... to make it possible to have different abelian group implementations available in Oscar.jl.
This is incomplete, and in particular has no tests, but I've had it sitting around for so long, I thought I should turn it into a PR so that either I feel pressured into finishing it, or someone else perhaps can help out :-) 
CC @thofma @ThomasBreuer
=> Add optional type argument to (free_)abelian_group

src/LocalField/LocalField.jl
=> promote to common type

src/LocalField/LocalField.jl
With this function, automorphism_group(L::UnramifiedLocalField) also works
=> Upadate_ResidueField_UnramifiedLocalField

test/LocalField/LocalField.jl
=> Test code for unramified extensions

Project.toml, src/Misc/CRT.jl, src/Misc/FiniteField.jl, src/Misc/Integer.jl, src/Misc/Matrix.jl, src/QuadForm/Enumeration.jl, src/RCF/rcf_stark.jl
This is the Hecke complement to https://github.com/Nemocas/AbstractAlgebra.jl/pull/980
Of course that PR needs to be merged before this one will pass.
=> Move solve with kernel to AbstractAlgebra

src/Map/MapType.jl, src/Misc/Series.jl, test/Map.jl, test/Map/MapFromFunc.jl
Afterwards, the following works.
```
julia> f = MapFromFunc(x -> x+1, x -> x-1, ZZ, ZZ);
julia> finv = inv(f);
julia> preimage(finv, ZZ(0))
1
```
=> set available inverse map in `inv(MapFromFunc)`

src/LocalField/LocalField.jl
optimal for large degree extension
=> optimize prime_field

.github/workflows/CI.yml, Project.toml, docs/src/index.md, src/Grp/SmallGroups.jl, src/Hecke.jl, test/LocalField/Conjugates.jl, test/runtests.jl
Note that Julia 1.6 is the new LTS release for Julia
See also https://github.com/Nemocas/Nemo.jl/pull/1213
=> Require Julia >= 1.6

examples/strassen.jl
currently needs square, power of 2
uses windows/ views
=> a geenric striassen mult. ripped from flint

examples/CharPoly.jl, src/Sparse/Row.jl
plus mul!, mul_red! in some of the sparse basics
=> a sparse spining based charpoly algo

src/QuadForm/Quad/GenusRep.jl, src/QuadForm/QuadBin.jl, test/QuadForm/QuadBin.jl
Implements automorphism group generators of binary quadratic forms of square discriminant and removes an erroneous assert
=> Automorphism group generators of binary quadratic forms

src/Misc/Matrix.jl, src/NumFieldOrd/NfOrd/Clgp/Types.jl, src/NumFieldOrd/NfOrd/Hensel.jl, src/NumFieldOrd/NfOrd/Ideal/Ideal.jl, src/NumFieldOrd/NfOrd/LLL.jl, src/NumFieldOrd/NfOrd/NfOrd.jl, src/NumFieldOrd/NfOrd/Unit/UnitGrpCtx.jl, src/QuadForm/ClosestVector.jl, src/QuadForm/PadicLift.jl, src/QuadForm/Quad/GenusRep.jl, src/QuadForm/Quad/Lattices.jl, src/QuadForm/Quad/Spaces.jl, src/QuadForm/Torsion.jl, test/QuadForm/ClosestVector.jl, test/QuadForm/PadicLift.jl, test/QuadForm/Quad/NormalForm.jl
- Remove more '
- Forgot one
- Remove more '
=> Remove more '

Project.toml, src/AlgAssAbsOrd/Ideal.jl, src/FunField/Round2.jl, src/GrpAb/GrpAbFinGen.jl, src/GrpAb/Map.jl, src/Hecke.jl, src/LocalField/Conjugates.jl, src/ModAlgAss/ModAlgAss.jl, src/NumField/NfAbs/NonSimple.jl, src/NumField/SimpleNumField/Subfields.jl, test/QuadForm/Quad/NormalForm.jl, test/QuadForm/Quad/ZLattices.jl
=> Remove compatibility code for get_special etc.

src/Misc/FiniteField.jl, src/NumField/NfAbs/MPolyAbsFact.jl, src/QuadForm/PadicLift.jl, src/Sparse/Matrix.jl, test/AlgAss/AbsAlgAss.jl, test/QuadForm/PadicLift.jl
and FiniteField always try to return the generator as well
=> RFS: systematically have GF return only the field

src/FieldFactory/ab_exts.jl, src/FieldFactory/conductors_generic.jl, src/NumFieldOrd/NfOrd/LLL.jl, test/RCF/rcf.jl
@fieker Kannst Du einmal drüber schauen? Ist nicht das eleganteste, sollte es aber tun.
=> Add signatures keyword for abelian_extensions

src/QuadForm/Herm/Lattices.jl, src/QuadForm/Lattices.jl, src/QuadForm/Quad/Lattices.jl, test/QuadForm/Lattices.jl
For lattice equality I am leaving a lot on the table performance wise, so please complain if it is too slow :)
=> Fix dual and add lattice equality

src/AlgAss/Types.jl, src/AlgAssAbsOrd/Types.jl, src/Hecke.jl, src/HeckeTypes.jl, src/Misc/OrdLocalization.jl
Makes the code more compact and also more efficient
=> Use AbstractAlgebra.get_cached!

src/GrpAb/Elem.jl, src/GrpAb/GrpAbFinGen.jl
This is a step towards getting Oscar (and Hecke) to comply to the conformance tests in GroupsCore.
=> Import GroupsCore.istrivial

src/NumField/NfAbs/NfAbs.jl, test/NfAbs/NfAbs.jl
(I'm still looking for the example)
=> typos in splitting field

test/runtests.jl
If using Revise when changing tests this is neccessary
=> rename exclude. It conflicts with exclude

src/NumFieldOrd/NfOrd/Ideal/Prime.jl
Huh, apparently I did not push the latest version of this branch for PR #576 :-(
=> Replace subgroup by sub

src/Sparse/Matrix.jl, src/Sparse/Trafo.jl, test/Sparse/Matrix.jl, test/Sparse/Trafo.jl
There was a bug in swap_cols!. I also added a size function.
Quick question. Is there a reason this doesn't subtype MatElem?
=> Sparse matrix bug fix

src/QuadForm/Herm/GenusRep.jl, src/QuadForm/Lattices.jl, test/QuadForm/Lattices.jl
and a small fix on a function (it is not tested since I haven't found any example to cover it, yet).
=> fixed ring for lattices

src/Hecke.jl
=> Fix Hecke.test_module(..., false)

src/NumField/NfAbs/Simplify.jl
would fix Gunters insanly large example - once lll is fixed...
=> increase precision as neccessary

docs/Build.jl, docs/Project.toml, docs/make.jl, docs/mkdocs.yml, docs/src/references.md
=> Fix bibliography

docs/Build.jl, docs/mkdocs.yml, docs/src/quad_forms/basics.md, docs/src/quad_forms/genusherm.md, docs/src/quad_forms/introduction.md, docs/src/quad_forms/lattices.md, src/QuadForm/Herm/Genus.jl, src/QuadForm/Herm/Lattices.jl, src/QuadForm/Herm/LocallyIsometricSublattice.jl, src/QuadForm/Herm/Spaces.jl, src/QuadForm/Lattices.jl, src/QuadForm/Quad/Lattices.jl, src/QuadForm/Quad/Spaces.jl, src/QuadForm/Spaces.jl
I haven't been able to create locally an experimental version of the webpage, so I am not sure about the final result. Yet, I have tried to use what have been done on the Oscar doc and some of the Hecke doc.
I have put many examples, for almost all the functions presented in the documentation. I am not strict on that: if it is too much I could remove/change some of them.
=> Changes on html doc for hermitian forms

src/NumField/NfAbs/Elem.jl
experimental? Do we want this?
=> allow to choose the factoring method over number fields

src/QuadForm/Quad/ZGenus.jl, test/QuadForm/Quad/ZGenus.jl
=> fix iseven(::ZpGenus)

src/NumField/NfAbs/NfAbs.jl, test/NfAbs/NfAbs.jl
Up to now, one got an error in the situation of the new test.
=> fixed comparison of `nf_elem` with different parents

src/QuadForm/Torsion.jl, test/QuadForm/Torsion.jl
Fix the creation of submodules of TorQuadMod if the cover it not full.
=> Fix sub for TorQuadMod

src/Misc/Matrix.jl, src/NumFieldOrd/NfOrd/LLL.jl
=> Merge isposdef into ispositive_definite

src/EllCrv/Finite.jl, src/EllCrv/Models.jl, test/EllCrv/Finite.jl
Also commented out some code that's no longer used, but I didn't want to delete quite yet.
=> Fixed trace of Frobenius. Added tests.

src/EllCrv/Isogeny.jl, src/EllCrv/Torsion.jl, test/EllCrv/Isogeny.jl
@JHanselman: Does that look good?
=> Add is_kernel_isogeny

src/EllCrv/EllCrv.jl, src/EllCrv/Finite.jl, src/EllCrv/Heights.jl, src/EllCrv/Isogeny.jl, src/EllCrv/Isomorphisms.jl, src/EllCrv/MinimalModels.jl, src/EllCrv/Misc.jl, src/EllCrv/Periods.jl, src/EllCrv/Torsion.jl, test/EllCrv/Isogeny.jl, test/EllCrv/Isomorphisms.jl, test/EllCrv/MinimalModels.jl, test/EllCrv/Torsion.jl
=> Adding lots of tests and removing unused code to increase coverage + bug

src/NumField/NfRel/NfRelNS.jl, test/NfRel/NonSimple.jl
Merge allows Non Simple extensions of relative number field to be created with vector of symbols,
also adds some basic tests for these types of extensions.
=> Updated NfRelNS with some accessors and tests

src/Sparse/Trafo.jl
Also handle type 7 in apply_left! and apply_right!
=> Add some SparseTrafoElem code comments

src/NumField/NfRel/NfRel.jl
Allows Constructing relative number field with a symbol
=> NfRel constructor accepting symbol

src/GrpAb/GrpAbFinGen.jl, src/LocalField/LocalField.jl, src/Misc/Infinity.jl, test/Misc.jl, test/Misc/Infinity.jl
- make `is_infinite` a synonym for `!isfinite`
- add some new methods for `PosInf` arguments
- fix some `isless` methods involving `PosInf`
- add `PosInf` tests
Resolves #705
=> Changes for is_infinite and PosInf

src/NumField/NfAbs/NfAbs.jl, test/NumField/NfAbs/NfAbs.jl
the 1st root was retunred in the "wrong" field
=> fix splitting field

src/EllCrv/Finite.jl, test/EllCrv/Finite.jl
This should fix trace_of_frobenius
=> Bugfix order_via_bsgs

src/AlgAss/AbsAlgAss.jl, src/AlgAss/AlgGrp.jl, src/AlgAssAbsOrd/Ideal.jl, src/AlgAssAbsOrd/LocallyFreeClassGroup.jl, test/AlgAssAbsOrd/LocallyFreeClassGroup.jl
- Unit group generators for finite algebras
- More assertions
=> Minor fixes and improvements for orders/ideals

Project.toml, docs/src/function_fields/degree_localization.md, examples/Round2.jl, src/FunField/DegreeLocalization.jl, src/FunField/Divisor.jl, src/FunField/IntClsZx.jl, src/GenOrd/GenOrd.jl, src/Misc/OrdLocalization.jl, src/NumField/NfAbs/NormRelation/Setup.jl, test/FunField/DegreeLocalization.jl, test/GenOrd/MaximalOrder.jl, test/Misc/Localization.jl, test/Misc/OrdLocalization.jl
=> Change Localization to localization

src/QuadForm/Torsion.jl, test/QuadForm/Torsion.jl
=> `orthogonal_sum` for `TorQuadMod`

src/QuadForm/Misc.jl, src/QuadForm/Spaces.jl, test/QuadForm/Lattices.jl
This reverts commit eea4cf32847951d673093ee5c116de64231f7d2c.
=> Revert "`VecSpaceRes` as `HeckeMap` (#835)"

src/QuadForm/Misc.jl, src/QuadForm/Spaces.jl, test/QuadForm/Lattices.jl
=> New `SpaceRes` struct

src/QuadForm/Misc.jl
This should resolve the tests non passing in #849
=> Add missing exports

src/NumFieldOrd/NfOrd/LinearAlgebra.jl, test/QuadForm/Lattices.jl
Fix also the containment check which accepts a matrix.
=> Fix #859 take 2

src/RCF/autos.jl, src/RCF/conductor.jl, src/RCF/cyclo.jl, test/RCF/rcf.jl
2 hard examples are known to work:
r = ray_class_field(27*maximal_order(quadratic_field(42)[1]))
s = ray_class_field(5*maximal_order(quadratic_field(3)[1]))
=> fixes (hopefully) the automorphisms

src/GrpAb/Elem.jl, src/Misc/Matrix.jl, src/QuadForm/Quad/GenusRep.jl, src/QuadForm/Quad/PadicLift.jl, src/QuadForm/Quad/ZGenus.jl, src/QuadForm/Quad/ZLattices.jl
This reverts commit acf8b38141f6d43c382164963dfcd6ca11406eda.
=> Revert "Temporarily remove some definitions (#868)"

docs/src/quad_forms/lattices.md, src/QuadForm/Herm/GenusRep.jl, src/QuadForm/Lattices.jl, src/QuadForm/Quad/GenusRep.jl, src/QuadForm/Quad/ZLattices.jl, src/QuadForm/QuadBin.jl, src/QuadForm/Torsion.jl, test/QuadForm/Herm/Genus.jl, test/QuadForm/Herm/GenusRep.jl, test/QuadForm/Herm/Lattices.jl, test/QuadForm/Quad/ZLattices.jl
=> separate is_isometric and is_isometric_with_isometry

src/Hecke.jl, src/Misc/PIDIdeal.jl
=> Adjust to new fallback for AA.factor

src/AlgAssAbsOrd/Conjugacy/Conjugacy.jl, test/AlgAssAbsOrd/Conjugacy/Conjugacy.jl
- Add the possibility to have different order for the matrices on the left and the right.
- Add some tests from representation theory.
=> More on `_basis_of_commutator_algebra`

docs/src/quad_forms/integer_lattices.md, src/NumField/QQ.jl, src/QuadForm/Quad/ZLattices.jl, test/QuadForm/Quad/ZLattices.jl
I do not know whether it is the most efficient way, but it should do the job.
=> Add divisibility in `ZLat`

src/AlgAssAbsOrd/UnitGroup.jl, src/HeckeTypes.jl, src/NumFieldOrd/NfOrd/Clgp.jl, src/NumFieldOrd/NfOrd/FacElem.jl, src/NumFieldOrd/NfOrd/Ideal/Ideal.jl, src/NumFieldOrd/NfOrd/Overorders.jl, src/NumFieldOrd/NfOrd/PicardGroup.jl, test/AlgAssAbsOrd/PicardGroup.jl, test/NfOrd/PicardGroup.jl, test/NfOrd/ResidueRing.jl
- unit_group_fac_elem for orders in etale algebras
- unit_group_fac_elem for non-maximal orders
- projection of factored elements for all orders in number fields or etale algebras
=> Improvements for unit groups and residue ring projections

src/Aliases.jl
Add aliases to the recent change of namings I have done
=> Add aliases of recent changes

src/Misc/Integer.jl
`carmichael_lambda` gave an error on input 1 and the wrong result for input 4, 24, 48, etc, this should fix all methods.
=> fix carmichael_lambda

src/Misc/Matrix.jl, src/Sparse/Trafo.jl
Nothing really uses (needs?) it
=> Remove coefficient_type

src/Hecke.jl
Needed for https://github.com/Nemocas/Nemo.jl/pull/1403
=> Avoid direct access to base_ring member

src/AlgAss/AbsAlgAss.jl, src/NumField/InfinitePlaces.jl, src/QuadForm/Torsion.jl
(lets hope that the tests succeed)
x-ref: https://github.com/oscar-system/Oscar.jl/pull/2083
=> jldoctest: add some missing end markers

src/NumField/NfRel/NfRel.jl, src/NumField/QQ.jl, src/QuadForm/Lattices.jl, src/QuadForm/Misc.jl, src/QuadForm/Spaces.jl, test/QuadForm/Lattices.jl
To avoid having a too big PR with a lot of noise, I have cut it in half: this first part is only about pure implementation. I will keep the parts about documentation, reorganisation and general clean-up for later. 
@simonbrandhorst  this one should be more digest and only focus on the important points
=> Implementation of trace equivalence for lattices with isometry

src/Misc/Matrix.jl
Resolves https://github.com/oscar-system/Oscar.jl/issues/2061
=> Allow `diagonal_matrix(QQ, [1, -1, -1])`

Project.toml, examples/Round2.jl, src/FunField/HessQR.jl
=> Remove dense_poly_type methods

src/Misc/MSet.jl, src/NumFieldOrd/NfOrd/LLL.jl
=> add edge-case-handling for `subsets`

src/ModAlgAss/MeatAxe.jl
It was messing up some docstrings.
=> make closure more restrictive

.github/workflows/oscar.yml, src/NumFieldOrd/NfOrd/Clgp/Map.jl, test/RCF/rcf.jl
triggered by
using Oscar
Qx, x = QQ["x"]
a=[310257,x^3-69*x-52,1,[]]
bnd=fmpz(10)^11
k, _ = number_field(a[2])
L = abelian_extensions(k, [2], bnd)
print(L)
for b in L
c=absolute_simple_field(number_field(b))[1];
println(defining_polynomial(c), ",")
end
(from Gunter)
=> yet another root vs iroot

src/FieldFactory/rayclassgrp.jl
See the comment in the source. Here is a script to exhibit the original
problem:
using Hecke
Qx, x = QQ["x"]
str="""
[148,x^3-x^2-3*x+1,1,[]],
"""
ll = [eval(Meta.parse(line[1:length(line)-1])) for line in split(str)]
for a = reverse(ll)
println("!")
bnd=5*fmpz(10)^9
k, _ = number_field(a[2])
L = abelian_extensions(k, [2], bnd, signatures=[(4,1),(6,0)])
end
=> Fix a performance bug in abelian_extensions

src/QuadForm/Lattices.jl, src/QuadForm/Quad/ZLattices.jl, src/QuadForm/Spaces.jl, src/QuadForm/Torsion.jl, test/QuadForm/Quad/Spaces.jl
=> Remove unneccessary argument checks

Project.toml, docs/Project.toml, docs/make.jl, src/Hecke.jl, test/EllCrv/Finite.jl, test/NfOrd/Clgp.jl, test/Project.toml, test/Sparse/Matrix.jl, test/parallel.jl, test/runtests.jl, test/setup.jl, test/testdefs.jl
See https://github.com/oscar-system/Oscar.jl/issues/2385.
Additionally does the same improvements to docs/Project.toml.
=> Move test dependencies to `test/Project.toml`

src/Misc/Poly.jl, src/NumField/NfAbs/PolyFact.jl, test/NfAbs/Elem.jl
=> Fix normalization bugs in factorization

docs/src/quad_forms/discriminant_group.md, src/GrpAb/Dual.jl, src/Misc/FiniteField.jl, src/QuadForm/Quad/ZLattices.jl, src/QuadForm/Torsion.jl, test/GrpAb/Dual.jl, test/QuadForm/Torsion.jl
- Add negation for QmodnZ
- Fix duplicated methods
- Add is_totally_isotropic for TorQuadMod and export gram_matrix_bilinear/gram_matrix_quadratic
- Trivial optimization for
- Add is_isometry, is_anti_isometry and submodules
=> Minor things for QuadForm

src/Misc/FiniteField.jl, test/Misc/FiniteField.jl
=> splitting field over fin. field

src/NumField/NfAbs/MPolyFactor.jl
by translating to abs-simple case
=> allow more general factor (MPoly over number field)

src/QuadForm/Quad/ZGenus.jl, test/QuadForm/Quad/ZGenus.jl
=> Fix printing `LocalZZGenus`

src/GrpAb/Elem.jl
This reverts commit 782291bec6dda68de84fb7b3d5de269e39505dff.
=> Revert "set the name more properly to help Janko (#1106)"

src/GrpAb/Elem.jl
This reverts commit b872137bf90ee0f602535930b003ce9d2430ec45.
=> Revert "Revert "set the name more properly to help Janko (#1106)" (#1118)"

src/QuadForm/QuadBin.jl, test/QuadForm/QuadBin.jl
=> Address Issue #1159

.github/workflows/CI.yml, .github/workflows/oscar.yml, test/runtests.jl
Cf. https://github.com/oscar-system/Oscar.jl/pull/2533
=> Update julia versions in CI

docs/src/sparse/intro.md, examples/NfMat.jl, src/AlgAss/AbsAlgAss.jl, src/AlgAss/Ideal.jl, src/AlgAssAbsOrd/Order.jl, src/GrpAb/ChainComplex.jl, src/HeckeTypes.jl, src/LinearAlgebra/FakeFmpqMat.jl, src/Misc/OrdLocalization.jl, src/Misc/serialize.jl, src/NumField/Elem.jl, src/NumField/NfAbs/NonSimple.jl, src/NumField/NfRel/NfRel.jl, src/NumField/NfRel/NfRelNS.jl, src/NumFieldOrd/NfOrd/Clgp/Proof.jl, src/NumFieldOrd/NfOrd/Elem.jl, src/NumFieldOrd/NfOrd/LinearAlgebra.jl, src/Sparse/Matrix.jl, src/Sparse/Trafo.jl, src/analytic.jl, test/RCF/rcf.jl
Solve the Hecke part of https://github.com/oscar-system/Oscar.jl/issues/2447.
=> Allow `AbstractUnitRange`

src/QuadForm/Herm/Genus.jl, src/QuadForm/Herm/Lattices.jl, src/QuadForm/Lattices.jl, src/QuadForm/Quad/Genus.jl, src/QuadForm/Quad/ZGenus.jl, test/QuadForm/Herm/Genus.jl, test/QuadForm/Quad/Genus.jl
Some of the `reduce` were buggy when one has to reduce an empty collection. Change some comparisons into an `init`.
=> Few more fixes in `QuadForm`

src/EllCrv/EllCrv.jl, src/EllCrv/Finite.jl, src/Grp/Agnostic.jl, src/Hecke.jl, src/Misc/UnitsModM.jl, test/EllCrv/Finite.jl
- Implement hashing
- Enable discrete logarithm
- Compute group structure for elliptic curves over finite fields
@JHanselman Does that make sense?
=> Improvements for elliptic curves

src/GrpAb/Map.jl
(after CF-WorkInProgress is in)
=> fix preimage. This Fix is tested by is_neat

.github/workflows/CI.yml, .github/workflows/CILong.yml
https://github.com/oscar-system/Oscar.jl/pull/2770 for Hecke. This is recommended by the [readme](https://github.com/julia-actions/julia-buildpkg#usage).
=> CI: use concrete action version

Project.toml, src/GrpAb/GrpAbFinGen.jl, src/GrpAb/SubgroupEnum.jl, src/Misc/Matrix.jl, src/QuadForm/Quad/ZLattices.jl, src/QuadForm/Torsion.jl, src/QuadForm/Types.jl
=> Bump version and AbstractAlgebra and Nemo compats

Project.toml, docs/Project.toml, test/Project.toml
Adapt for upcoming changes in julia nightly, see:
https://discourse.julialang.org/t/psa-compat-requirements-in-the-general-registry-are-changing/104958
=> Add compat entries for all deps (even stdlibs)

.github/workflows/CILong.yml, src/HeckeTypes.jl, src/NumFieldOrd/NfOrd/Clgp.jl, src/NumFieldOrd/NfOrd/Clgp/Ctx.jl, src/NumFieldOrd/NfOrd/Clgp/FacBase_Idl.jl, src/NumFieldOrd/NfOrd/Clgp/Proof.jl, src/NumFieldOrd/NfOrd/Ideal/Ideal.jl, test/runtests.jl, test/threads.jl
- Make some things more thread safe
- Parallel class group proof
- Clean up docstring for `class group`
=> Improve class group proof

src/AlgAssAbsOrd/ICM.jl, src/HeckeTypes.jl, src/NumFieldOrd/NfOrd/Elem.jl, test/NfOrd/Ideal.jl
=> Fix bug in power_mod and is_zero(::Ideal)

test/Aqua.jl, test/Project.toml
Furthermore some cleanup after #1131.
=> Bump Aqua to 0.8 and use defaults

src/GrpAb/stable_sub.jl, src/Misc/jordan.jl, src/NumField/Subfields.jl
Extracted from #1294, which may require a bit more time to complete.
CC @lgoettgens @thofma
=> Replace some `vcat` and `hcat` calls by `reduce`

Project.toml, src/NumField/Embedded.jl, test/NumField/Embedded.jl
Just foward the methods to the underlying number fiel.
=> feat: add roots/factor for embedded field polys

examples/NFDB.jl, src/LocalField/Conjugates.jl
Also use it in the _p_adic_regulator function
=> feat: add precision argument for completion_easy

docs/src/quad_forms/genusherm.md, src/QuadForm/Herm/Genus.jl, test/QuadForm/Herm/Genus.jl
=> Add norm and scale for `HermGenus`

Project.toml, ext/GAPExt/abelian_layer.jl, ext/GAPExt/fields.jl, src/HeckeTypes.jl, src/exports.jl
Also introduces the `const`/alias `AbsSimpleNumFieldOrderFractionalIdeal`
=> Some more renamings

src/LocalField/qAdic.jl, src/NumFieldOrd/NfOrd/ResidueField.jl
requires Nemo PR 1663 to enable attributes on p and q adics
replaces PR #1374
=> fewer check and more cache for residue fields

src/Sparse/Rref.jl, test/Sparse/Rref.jl
Things I overlooked in #1401 and which turn up in the OSCAR tests. Sorry.
=> Leftovers from linear solving

src/NumField/NfAbs/MPolyGcd.jl, test/NfAbs/MPolyGcd.jl, test/NumField/NfAbs/MPolyFactor.jl
- handle the case of non-nice defining polynomial better
=> fix: multivariate gcd over number fields

src/AlgAss/AlgMatElem.jl
=> feat: improve matrix algebra code

src/Grp/GenGrp.jl
Don't mention implementation details, but do describe the
return values. Also add a doctest example.
=> Tweak generic_group docstring

Project.toml, src/NumField/ComplexEmbeddings/Generic.jl, src/NumField/ComplexEmbeddings/QQ.jl, src/NumField/NfAbs/Conjugates.jl, test/NfAbs/Conjugates.jl, test/NumField/ComplexEmbeddings/Generic.jl, test/NumField/ComplexEmbeddings/QQ.jl
- Allow arbitrary NumField
- Allow totally real fields
- Allow QQ
=> feat: extend methods for complex_conjugation

src/HeckeTypes.jl
Reported (and fixed) by Markus Kirschmer.
=> fix: avoid costly converions

test/Misc/jordan_test.jl
See https://github.com/Nemocas/AbstractAlgebra.jl/pull/1662
=> Adjust a test

.github/workflows/DeployDocs.yml, .github/workflows/DocCleanUp.yml
- Mitigate https://github.com/LuxDL/DocumenterVitepress.jl/issues/81
- Keep the `gh-pages` branch small
=> chore: add some github workflows

Project.toml, examples/NFDB.jl, test/LocalField/Completions.jl
- **fix: precision problem in p-adic regulator**
- **chore: bump to 0.30.9**
=> fix: precision problem in p-adic regulator

src/Grp/GenGrp.jl
- Parent objects should use ===
=> fix: remove erroneous equality check for groups

src/NumFieldOrd/NfOrd/FracIdeal.jl, src/NumFieldOrd/NfOrd/Ideal/Ideal.jl, src/NumFieldOrd/NfOrd/Ideal/TwoElement.jl, src/NumFieldOrd/NfRelOrd/FracIdeal.jl, src/NumFieldOrd/NfRelOrd/Ideal.jl, src/QuadForm/Misc.jl, test/NfOrd/FracIdl.jl, test/NfOrd/Ideal.jl, test/NfRel/FracIdeal.jl, test/NfRel/Ideal.jl
- closes https://github.com/thofma/Hecke.jl/issues/1330
- absolute and relative case
- integral and fractional ideals
=> fix: basis and basis matrix of zero ideal

src/FieldFactory/conductors_generic.jl, test/RCF/conductor_sieve.jl
- use AVL tree instead of Vector with repeated insert! calls
=> feat: faster conductors

src/Hecke.jl
Resolves https://github.com/thofma/Hecke.jl/issues/1472.
cc @fingolfin
=> Use banner showing code from AbstractAlgebra

src/LocalField/LocalField.jl, src/Misc/RelFiniteField.jl, src/NumField/Field.jl, src/NumField/NfAbs/NfAbs.jl, src/NumField/NfAbs/NonSimple.jl, src/NumField/NfRel/NfRel.jl, src/NumField/NfRel/NfRelNS.jl, src/NumField/NonSimpleNumField/Field.jl, src/NumField/SimpleNumField/Field.jl, test/LocalField/LocalField.jl, test/Misc/NumberField.jl, test/Misc/RelFinField.jl
=> Use Varname to simplify some code

Project.toml, src/AlgAss/AlgMat.jl, src/AlgAss/radical.jl, src/NumFieldOrd/NfOrd/PicardGroup.jl, src/QuadForm/Misc.jl
... resp. trigger points for method invalidations
=> Avoid some type instability issues

src/QuadForm/Lattices.jl, src/QuadForm/Quad/ZGenusRep.jl, src/QuadForm/Quad/ZLattices.jl
And allow to read `automorphism_group_order` stored from external knowledge.
=> Fix `load_genus`

src/QuadForm/Herm/GenusRep.jl, test/QuadForm/Herm/GenusRep.jl
There was an issue which was not covered by the previous tests.
=> Fix `genus_representatives` for rank 1 `HermLat`

src/LocalField/Ring.jl
Resolves https://github.com/thofma/Hecke.jl/issues/1535.
=> Fix printing of LocalFieldValuationRingElem as poly coeffs

src/Misc/Matrix.jl, src/Misc/jordan.jl, test/Misc/Matrix.jl
Now all _copy_matrix_into_matrix are next to each other and the
one for QQMatrix has the right name
=> Collect _copy_matrix_into_matrix methods, fix name of one

src/AlgAss/AlgMatElem.jl, test/AlgAss/Elem.jl
=> fix: wrong addeq! for MatAlgebraElem

src/AlgAss/AlgQuat.jl, src/NumFieldOrd/NfOrd/LLL.jl
- cache only if the weights are trivial
=> fix: bug in short_elem of trivial ideal

src/Sparse/Row.jl
I missed a small spacing error that should have been corrected in [1322](https://github.com/thofma/Hecke.jl/pull/1322)
=> spacing for docs block

src/AlgAssAbsOrd/LocallyFreeClassGroup.jl, src/NumFieldOrd/NfOrd/ResidueRingMultGrp.jl
- compute the idempotents in the center
=> feat: improve locally free class group

Project.toml, src/Misc/QQBar.jl, test/Misc/QQBar.jl
- feat: add roots for polynomials over algebraic_closure(QQ)
- chore: bump to 0.33.2
=> Add roots for polynomials over algebraic closure of QQ

src/HeckeTypes.jl, src/NumFieldOrd/NfOrd/FracIdeal.jl, test/NfOrd/FracIdl.jl
=> feat: add `copy` keyword to basis of fractional ideals

.github/workflows/CI.yml, .github/workflows/oscar.yml
Cf. https://github.com/oscar-system/Oscar.jl/issues/4072
=> Daily tests

test/RCF/rcf.jl
Closes #1625
(the example is smaller)
=> test: add example for #1629

README.md, src/Hecke.jl
I only recently found out that Hecke has its own manual. I included the manual link in the banner, similarly to the Julia and OSCAR banners.
=> Update Hecke banner

src/HeckeTypes.jl, src/Misc/FactoredElem.jl
FacElemMon is a monoid, not a ring
=> Minor cleanup related to FacElemMon and FacElem

src/GrpAb/stable_sub.jl
Observed in https://github.com/Nemocas/Nemo.jl/actions/runs/12706975244/job/35420988888#step:7:394
=> Remove output during tests

Project.toml
=> chore:bump to 0.35.9

Project.toml, src/AlgAss/AbsAlgAss.jl, src/exports.jl, test/AlgAss/AbsAlgAss.jl
=> feat: add separability for algebras (commutative only for now)

docs/src/howto/reduction.md, docs/src/index.md, docs/src/manual/abelian/elements.md, docs/src/manual/abelian/structural.md, docs/src/manual/elliptic_curves/intro.md, docs/src/manual/misc/FacElem.md, docs/src/manual/misc/pmat.md, docs/src/manual/number_fields/class_fields.md, docs/src/manual/number_fields/complex_embeddings.md, docs/src/manual/number_fields/internal.md, docs/src/manual/orders/elements.md, docs/src/manual/orders/frac_ideals.md, docs/src/manual/orders/ideals.md, docs/src/manual/quad_forms/lattices.md
- fix some typos
- expand abbreviations
- fix MathJax rendering of a formula
- change a langle to rangle
- some stylistic changes
=> Some minor documentation improvements

Project.toml, src/FunField/Factor.jl
- this is now provided in AbstractAlgebra/Nemo
=> fix: remove redundant factor function

docs/src/.vitepress/theme/style.css
- mirro https://github.com/LuxDL/DocumenterVitepress.jl/pull/221
=> fix: tweak CSS

src/FunField/Factor.jl, src/LinearAlgebra/Semilinear.jl, test/FunField.jl, test/FunField/Factor.jl
- implement missing squarefree factorization a la Gianni-Trager
- so far only if the transcendental element/basis is separating
CC: @wfsteiner
=> feat: factorization for polynomial over function fields

src/AlgAss/Decompose.jl, test/AlgAss/Decompose.jl
=> feat: allow inseparable algebras when decomposing

src/ModAlgAss/ModAlgAss.jl
=> Update error in GAPExt function stubs

ext/GAPExt/meataxe.jl, src/ModAlgAss/ModAlgAss.jl
Final Hecke part of https://github.com/oscar-system/Oscar.jl/issues/4625.
=> Remove calls to `gap_to_julia` in meataxe

src/Misc/Poly.jl, src/exports.jl
=> Add `is_cyclotomic_polynomial_with_data`

Project.toml, src/FunField/Factor.jl, test/FunField/Factor.jl
=> feat: factoring over inseparable extensions

src/Misc/Integer.jl, test/Misc/Integer.jl
- 1 needs special treatment
Closes #1780
=> fix: euler_phi_inv(1)

src/AlgAss/AlgQuat.jl, test/AlgAss/AlgQuat.jl
- these are not quaternion algebras, so don't allow constructing them
=> fix: quaternion algebras in characteristic 2

src/AlgAss/AlgGrp.jl, src/AlgAss/AlgMat.jl, src/AlgAss/AlgMatElem.jl, src/AlgAss/Ideal.jl, src/AlgAss/Torus.jl, src/AlgAss/radical.jl, src/AlgAssAbsOrd/Ideal.jl, src/AlgAssAbsOrd/LocallyFreeClassGroup.jl, src/AlgAssAbsOrd/Order.jl, src/AlgAssAbsOrd/PIP/bley_hofmann_johnston.jl, src/AlgAssAbsOrd/PIP/maximal.jl, src/AlgAssAbsOrd/PIP/unit_group_generators.jl, src/AlgAssRelOrd/Eichler.jl, src/AlgAssRelOrd/Ideal.jl, src/AlgAssRelOrd/Order.jl, src/ModAlgAss/Lattices/Basics.jl
- maybe later we find a better name for the user-facing version
=> fix: rename degree(::MatAlgebra) to _matdeg

src/AlgAss/AlgQuat.jl, src/AlgAssAbsOrd/PIP/unit_group_generators.jl, src/Deprecations.jl, test/AlgAss/AlgQuat.jl
- improve printing
- rename `is_quaternion_algebra`
=> Improvements for quaternion algebra (elements)

src/LocalField/Completions.jl, src/LocalField/automorphisms.jl, src/LocalField/map.jl, test/LocalField/LocalField.jl
(also add experimental _is_locally_isomorphic for number fields)
=> feat: add is_isomorphic for local fields

docs/src/manual/number_fields/fields.md, docs/src/manual/number_fields/intro.md, src/NumField/Field.jl, src/NumField/SimpleNumField/Field.jl
I collect everything I find while reading the Number theory part of the oscar docs.
=> Fix some docs typos

src/AlgAss/AlgQuat.jl, src/exports.jl, test/AlgAss/AlgQuat.jl
=> Add `quaternion_algebra` constructor

docs/src/.vitepress/config.mts, docs/src/manual/algebras/basics.md, docs/src/manual/algebras/groupalgebras.md, docs/src/manual/algebras/quaternion.md, docs/src/manual/algebras/structureconstant.md, src/AlgAss/AlgQuat.jl, src/AlgAss/Elem.jl, src/QuadForm/Quad/Spaces.jl, src/exports.jl, test/AlgAss/AlgQuat.jl
- add `is_split_with_zero_divisor`
- add documentation
=> feat: enhance functionality for quaternion algebras

.github/workflows/CILong.yml
=> ci: run long tests on one thread

src/NumFieldOrd/NfRelOrd/Ideal.jl, test/NfRel/Ideal.jl
Make it not throw if the answer is no.
=> fix: in(::NumFieldElem, ::OrderIdeal)

src/AlgAssAbsOrd/Elem.jl
(don't check whether the result is an element of the order)
=> perf: make order element arithmetic faster

src/QuadForm/Herm/GenusRep.jl, test/QuadForm/Herm/GenusRep.jl
=> fix: rescaling of form in neighbour method

src/QuadForm/Herm/Mass.jl, test/QuadForm/Herm/Mass.jl
- Use the correct division function in case dividend is negative
- Closes #1857
=> Fix `local_factor` for Hermitian lattices

src/NumField/NfAbs/Elem.jl, test/Misc/QQBar.jl
=> add norm(poly) of constant poly

docs/src/manual/number_fields/class_fields.md, docs/src/manual/orders/ideals.md, src/NumFieldOrd/NfOrd/Clgp/Map.jl, src/NumFieldOrd/NfOrd/FracIdeal.jl
This resolves the first bullet point of https://github.com/oscar-system/Oscar.jl/issues/4935.
=> Slightly improve printing of `MapClassGrp`

docs/src/manual/algebras/basics.md, docs/src/manual/algebras/quaternion.md, src/AlgAss/AlgQuat.jl, test/AlgAss/AlgQuat.jl
Added a definition for quaternion algebras in characteristic 2.
(Tried some of the functionality with characteristic 2 algebras. The standard involution works as is --
but I was wondering if there was a reason it wasn't hard coded?)
=> Added quaternions in characteristic 2

Project.toml, src/AlgAssAbsOrd/PIP/unit_group_generators.jl, test/AlgAssAbsOrd/PIP/unit_group_generators.jl
- **fix: GRH for unit_group_generators of orders**
- **chore: bump to 0.37.4**
=> Enable more GRH options

src/NumField/NfRel/NfRelNS.jl, test/NumField/NfRel.jl, test/NumField/NfRel/NfRelNS.jl
This pull requests adds the resultant methods for universal polynomial rings as well as some tests for it. (Probably this should be a part of AbstractAlgebra at some point...)
=> Add resultant for univariate polynomials

src/QuadForm/Quad/GenusRep.jl, test/QuadForm/Quad/GenusRep.jl
Thankfully the check in the assertion was just wrong.
Closes #1939
=> fix: wrong index in _padic_index

src/NumField/NfAbs/MultDep.jl
Ideally I should try to construct examples, but the original ones are lost due to them having been part of a long and complicated construction
=> fix some corner cases that were fixed on the fly..

src/NumFieldOrd/NfOrd/Clgp.jl, src/exports.jl, test/NfOrd/Clgp.jl
- add and export `class_number`
Closes #1967
=> fix: disallow non-maximal orders in `class_group`

src/GrpAb/stable_sub.jl, test/Misc/stable_subgroups.jl
=> fix: cornercase in stable_subgroup

src/AlgAss/AlgMat.jl, test/AlgAss/AlgMat.jl
=> feat: add iteration in matrix algebras over finite fields

src/NumFieldOrd/NfOrd/FracIdeal.jl, src/NumFieldOrd/NfOrd/Ideal/Prime.jl, test/NfOrd/FracIdl.jl, test/NfOrd/Ideal.jl
- generalize `fractional_ideal` construtor
- add is_subset for (fractional) ideals
Closes #2003
=> feat: improvements for (fractional) ideals

src/HeckeTypes.jl, src/Sparse/Row.jl
This is a small chunk of things I played around with today to speed up some computations. I was wondering whether this is interesting in general. If you like it, feel free to take it in. 
I will add an example showcasing the benefit.
=> Add some size_hint for sparse rows
